# **Predicting Earth-Like Similarity in Exoplanets: Modeling Experiments**

## **Preparing the Dataset for Modeling**

In [ ]:
# general importing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# K-Nearest Neighbor importing
from sklearn.impute import KNNImputer
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline

# regex importing for pattern recognition
import re

In [ ]:
# loading dataset
new_exoplanets_filtered4 = pd.read_csv('/content/drive/MyDrive/Exoplanet /filtered_2026_dataset_new_final3.csv')

In [ ]:
new_exoplanets_filtered4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5419 entries, 0 to 5418
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   planet_name                   5419 non-null   object
 1   star_number_per_system        5419 non-null   float64
 2   spectral_type                 5419 non-null   object
 3   orbital_period_day            5419 non-null   float64
 4   orbit_semi_major_axis_au      5419 non-null   float64
 5   planet_rad_earth_rad          5419 non-null   float64
 6   planet_mass_earth_mass        5419 non-null   float64
 7   planet_equil_temp_k           5419 non-null   float64
 8   stellar_effective_temp_k      5419 non-null   float64
 9   stellar_rad_solar_rad         5419 non-null   float64
 10  stellar_mass_solar_mass       5419 non-null   float64
 11  stellar_surf_grav             5419 non-null   float64
 12  stellar_luminosity_solar_lum  5419 non-null   float64
 13  planet_orbital_velocity       5419 non-null   float64
 14  habitable_zone_main_seq       5419 non-null   int64
dtypes: float64(12), int64(1), object(2)
memory usage: 635.2+ KB

In [ ]:
# viewing all rows which are within the habitable zone of its star
new_exoplanets_filtered4[new_exoplanets_filtered4['habitable_zone_main_seq'] == 1]

,planet_name,star_number_per_system,spectral_type,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
28,55 Cnc f,2.0,GV,260.78125,0.781513,6.344191,47.529849,235.917959,5241.127143,0.963067,0.924286,4.412356,0.627916,1.087703,1
45,AU Mic e,1.0,KV,33.25000,0.170681,4.301580,21.100000,325.735064,3665.000000,0.820000,0.600000,4.520000,0.108846,1.875246,1
59,BD+49 828 b,1.0,KV,2590.00000,4.200000,19.718599,508.500000,269.617897,4943.000000,7.600000,1.520000,2.850000,30.937091,0.601689,1
64,BD-11 4672 c,1.0,KV,74.20000,0.300000,3.696464,15.370000,269.263294,4550.000000,0.639000,0.651000,4.642000,0.157014,1.473346,1
143,EPIC 212737443 c,1.0,KV,65.55000,0.280000,2.690000,6.554346,316.000000,4684.000000,0.673000,0.690000,4.622000,0.195608,1.570075,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4961,TOI-4633 c,2.0,GV,271.94450,0.847000,3.200000,123.000000,261.852602,5800.000000,1.050000,1.100000,4.436836,1.119387,1.139803,1
4978,TOI-500 e,1.0,KV,61.30000,0.275206,3.659440,15.050000,282.582374,4440.000000,0.678000,0.740000,4.618000,0.160281,1.640069,1
5016,TOI-544 c,1.0,KV,50.08900,0.228093,4.340406,21.500000,279.380615,4169.000000,0.623000,0.631000,4.680000,0.105195,1.663543,1
5097,TOI-712 d,1.0,KV,84.83960,0.340500,2.474000,5.590613,313.600000,4622.000000,0.674000,0.732000,4.645000,0.186007,1.466466,1
5289,WASP-41 c,1.0,GV,421.00000,1.070000,27.391649,1010.699400,241.000000,5545.000000,0.870000,0.930000,4.530000,0.641999,0.932448,1

In [ ]:
# viewing row for kepler-452 b
new_exoplanets_filtered4[new_exoplanets_filtered4['planet_name'] == 'Kepler-452 b']

,planet_name,star_number_per_system,spectral_type,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
3674,Kepler-452 b,1.0,GV,384.844831,1.009733,1.63,3.294107,235.0,5687.166667,1.099285,1.029667,4.44555,1.134212,1.009997,1

In [ ]:
# viewing row for Kepler-22 b
new_exoplanets_filtered4[new_exoplanets_filtered4['planet_name'] == 'Kepler-22 b']

,planet_name,star_number_per_system,spectral_type,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
3069,Kepler-22 b,1.0,GV,289.863821,0.829829,2.191111,9.1,264.142857,5589.090909,0.881097,0.951875,4.478131,0.679676,1.0712,1

In [ ]:
# viewing row for Kepler-1638 b
new_exoplanets_filtered4[new_exoplanets_filtered4['planet_name'] == 'Kepler-1638 b']

,planet_name,star_number_per_system,spectral_type,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
2534,Kepler-1638 b,1.0,GV,259.338308,0.78415,1.87,4.605677,328.75,5737.888889,0.95,0.917571,4.206098,0.877699,1.081921,1

-----------

# **Proposed Method K Nearest Neighbor (KNN) Models**
Used to idenfity the top 10 most Earth-Like Exoplanets by comparing all exoplanets (represented as datapoints) to a synthetically created "target row" Earth. The features of all exoplanets are then compared to the features of Earth based on the Manhattan Distance and the Euclidean Distance between data points. The closer the match (most Earth-Like) the smaller the distance from Earth.

Two KNN Models will be created. The first KNN Model will be using the Manhattan Distance. The second KNN Model will be using the Euclidean Distance. Both models will use the Minkowski DIstance which will be fine tuned based on if the value p=1 or p=2 which corresponds to the Manhatten Distance or Euclidean Distance respectively.

#### Preparing Dataset

In [ ]:
# creating copy of dataset for KNN Model
new_exoplanets_filtered_KNN = new_exoplanets_filtered4.copy()

#### Ensure all features are normalized in terms of Earth

In [ ]:
# Normalize the orbital period column
new_exoplanets_filtered_KNN['orbital_period_day'] = new_exoplanets_filtered_KNN['orbital_period_day'] / 365.26

# Normalize the planet equilibrium temperature
new_exoplanets_filtered_KNN['planet_equil_temp_k'] = new_exoplanets_filtered_KNN['planet_equil_temp_k'] / 255.0

# Normalize the stellar effective temperature
new_exoplanets_filtered_KNN['stellar_effective_temp_k'] = new_exoplanets_filtered_KNN['stellar_effective_temp_k'] / 5772.0

#### Creating Target Row for Earth

In [ ]:
# creating a target row called Earth which all the other rows will be compared to (similarity search)
earth = pd.DataFrame({'planet_name': ['Earth'],
                      'star_number_per_system': [1.0],
                      'orbital_period_day': [1.0],
                      'orbit_semi_major_axis_au':[1.0],
                      'planet_rad_earth_rad': [1.0],
                      'planet_mass_earth_mass': [1.0],
                      'planet_equil_temp_k': [1.0],
                      'spectral_type': ['GV'],
                      'stellar_effective_temp_k': [1.0],
                      'stellar_rad_solar_rad': [1.0],
                      'stellar_mass_solar_mass': [1.0],
                      'stellar_surf_grav': [1.0],
                      'stellar_luminosity_solar_lum': [1.0],
                      'planet_orbital_velocity': [1.0],
                      'habitable_zone_main_seq': [1]})

In [ ]:
earth

,planet_name,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
0,Earth,1.0,1.0,1.0,1.0,1.0,1.0,GV,1.0,1.0,1.0,1.0,1.0,1.0,1

In [ ]:
earth.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   planet_name                   1 non-null      object
 1   star_number_per_system        1 non-null      float64
 2   orbital_period_day            1 non-null      float64
 3   orbit_semi_major_axis_au      1 non-null      float64
 4   planet_rad_earth_rad          1 non-null      float64
 5   planet_mass_earth_mass        1 non-null      float64
 6   planet_equil_temp_k           1 non-null      float64
 7   spectral_type                 1 non-null      object
 8   stellar_effective_temp_k      1 non-null      float64
 9   stellar_rad_solar_rad         1 non-null      float64
 10  stellar_mass_solar_mass       1 non-null      float64
 11  stellar_surf_grav             1 non-null      float64
 12  stellar_luminosity_solar_lum  1 non-null      float64
 13  planet_orbital_velocity       1 non-null      float64
 14  habitable_zone_main_seq       1 non-null      int64
dtypes: float64(12), int64(1), object(2)
memory usage: 252.0+ bytes

#### Setting planet name as the index (since planet name is the observation)

In [ ]:
# set planet name as index for earth row
earth.set_index('planet_name', inplace=True)

# setting the planet_name as the index
new_exoplanets_filtered_KNN.set_index('planet_name', inplace=True)

In [ ]:
new_exoplanets_filtered_KNN.head()

,star_number_per_system,spectral_type,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
planet_name,,,,,,,,,,,,,,
11 Com b,2.0,GIII,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,90.778824,1.305879,0
11 UMi b,1.0,KIII,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,217.709668,1.349663,0
14 And b,1.0,KIII,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,63.134826,1.528982,0
14 Her b,1.0,KV,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,0.705033,0.566812,0
16 Cyg B b,3.0,GV,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,1.231895,0.782034,0

In [ ]:
earth.head()

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
planet_name,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,GV,1.0,1.0,1.0,1.0,1.0,1.0,1

In [ ]:
new_exoplanets_filtered_KNN.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5419 entries, 11 Com b to xi Aql b
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   star_number_per_system        5419 non-null   float64
 1   spectral_type                 5419 non-null   object
 2   orbital_period_day            5419 non-null   float64
 3   orbit_semi_major_axis_au      5419 non-null   float64
 4   planet_rad_earth_rad          5419 non-null   float64
 5   planet_mass_earth_mass        5419 non-null   float64
 6   planet_equil_temp_k           5419 non-null   float64
 7   stellar_effective_temp_k      5419 non-null   float64
 8   stellar_rad_solar_rad         5419 non-null   float64
 9   stellar_mass_solar_mass       5419 non-null   float64
 10  stellar_surf_grav             5419 non-null   float64
 11  stellar_luminosity_solar_lum  5419 non-null   float64
 12  planet_orbital_velocity       5419 non-null   float64
 13  habitable_zone_main_seq       5419 non-null   int64
dtypes: float64(12), int64(1), object(1)
memory usage: 635.0+ KB

In [ ]:
earth.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, Earth to Earth
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   star_number_per_system        1 non-null      float64
 1   orbital_period_day            1 non-null      float64
 2   orbit_semi_major_axis_au      1 non-null      float64
 3   planet_rad_earth_rad          1 non-null      float64
 4   planet_mass_earth_mass        1 non-null      float64
 5   planet_equil_temp_k           1 non-null      float64
 6   spectral_type                 1 non-null      object
 7   stellar_effective_temp_k      1 non-null      float64
 8   stellar_rad_solar_rad         1 non-null      float64
 9   stellar_mass_solar_mass       1 non-null      float64
 10  stellar_surf_grav             1 non-null      float64
 11  stellar_luminosity_solar_lum  1 non-null      float64
 12  planet_orbital_velocity       1 non-null      float64
 13  habitable_zone_main_seq       1 non-null      int64
dtypes: float64(12), int64(1), object(1)
memory usage: 120.0+ bytes

#### Encoding Categorical Columns
OneHotEncoder is used because it creates 21 new binary columns corresponding to the unique spectral type entries:
* GIII, KIII, KV, GV, GIV, KIV, MV, sdB, FIV, FV, KII, SD, AV, MIII, AIII, BV, AIV, WD, T, BIV, GII

So, for example:
* If spectral_type_GV == 1 --> may increase habitability probability
* If spectral_type_MV == 1 --> may increase habitability probability
* If spectral_type_WD == 1 --> may decrease habitability probability

In [ ]:
new_exoplanets_filtered_KNN['spectral_type'].unique()

array(['GIII', 'KIII', 'KV', 'GV', 'GIV', 'KIV', 'MV', 'sdB', 'FIV', 'FV',
       'KII', 'SD', 'AV', 'MIII', 'AIII', 'BV', 'AIV', 'WD', 'T', 'BIV',
       'GII'], dtype=object)

In [ ]:
# Combine both for fitting the OneHotEncoder to prevent unseen label errors
combined_spectral_type = pd.concat([new_exoplanets_filtered_KNN['spectral_type'], earth['spectral_type']], ignore_index=True)

# Ensure combined_spectral_type is a DataFrame with 1 column
combined_spectral_type_df = pd.DataFrame(combined_spectral_type, columns=['spectral_type'])

# Fit the OneHotEncoder for categorical columns
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoder.fit(combined_spectral_type_df)

# Transform both the original cleaned dataset and the earth target row dataset
new_exoplanets_filtered_KNN_encoded = encoder.transform(new_exoplanets_filtered_KNN[['spectral_type']])
earth_encoded = encoder.transform(earth[['spectral_type']])

# Generate column names for the encoded columns
encoded_columns = encoder.get_feature_names_out(['spectral_type'])

# Convert to DataFrame and ensure indices match
new_exoplanets_filtered_KNN_encoded = pd.DataFrame(
    new_exoplanets_filtered_KNN_encoded,
    columns=encoded_columns,
    index=new_exoplanets_filtered_KNN.index
)
earth_encoded = pd.DataFrame(
    earth_encoded,
    columns=encoded_columns,
    index=earth.index
)

# Drop orignal spectral_type column since we have generated encoded columns
new_exoplanets_filtered_KNN = new_exoplanets_filtered_KNN.drop(columns=['spectral_type'])
earth = earth.drop(columns=['spectral_type'])

# Add encoded columns back into original cleaned dataset and earth
new_exoplanets_filtered_KNN = pd.concat([new_exoplanets_filtered_KNN, new_exoplanets_filtered_KNN_encoded], axis=1)
earth = pd.concat([earth, earth_encoded], axis=1)

In [ ]:
new_exoplanets_filtered_KNN.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5419 entries, 11 Com b to xi Aql b
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   star_number_per_system        5419 non-null   float64
 1   orbital_period_day            5419 non-null   float64
 2   orbit_semi_major_axis_au      5419 non-null   float64
 3   planet_rad_earth_rad          5419 non-null   float64
 4   planet_mass_earth_mass        5419 non-null   float64
 5   planet_equil_temp_k           5419 non-null   float64
 6   stellar_effective_temp_k      5419 non-null   float64
 7   stellar_rad_solar_rad         5419 non-null   float64
 8   stellar_mass_solar_mass       5419 non-null   float64
 9   stellar_surf_grav             5419 non-null   float64
 10  stellar_luminosity_solar_lum  5419 non-null   float64
 11  planet_orbital_velocity       5419 non-null   float64
 12  habitable_zone_main_seq       5419 non-null   int64
 13  spectral_type_AIII            5419 non-null   float64
 14  spectral_type_AIV             5419 non-null   float64
 15  spectral_type_AV              5419 non-null   float64
 16  spectral_type_BIV             5419 non-null   float64
 17  spectral_type_BV              5419 non-null   float64
 18  spectral_type_FIV             5419 non-null   float64
 19  spectral_type_FV              5419 non-null   float64
 20  spectral_type_GII             5419 non-null   float64
 21  spectral_type_GIII            5419 non-null   float64
 22  spectral_type_GIV             5419 non-null   float64
 23  spectral_type_GV              5419 non-null   float64
 24  spectral_type_KII             5419 non-null   float64
 25  spectral_type_KIII            5419 non-null   float64
 26  spectral_type_KIV             5419 non-null   float64
 27  spectral_type_KV              5419 non-null   float64
 28  spectral_type_MIII            5419 non-null   float64
 29  spectral_type_MV              5419 non-null   float64
 30  spectral_type_SD              5419 non-null   float64
 31  spectral_type_T               5419 non-null   float64
 32  spectral_type_WD              5419 non-null   float64
 33  spectral_type_sdB             5419 non-null   float64
dtypes: float64(33), int64(1)
memory usage: 1.6+ MB

In [ ]:
earth.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, Earth to Earth
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   star_number_per_system        1 non-null      float64
 1   orbital_period_day            1 non-null      float64
 2   orbit_semi_major_axis_au      1 non-null      float64
 3   planet_rad_earth_rad          1 non-null      float64
 4   planet_mass_earth_mass        1 non-null      float64
 5   planet_equil_temp_k           1 non-null      float64
 6   stellar_effective_temp_k      1 non-null      float64
 7   stellar_rad_solar_rad         1 non-null      float64
 8   stellar_mass_solar_mass       1 non-null      float64
 9   stellar_surf_grav             1 non-null      float64
 10  stellar_luminosity_solar_lum  1 non-null      float64
 11  planet_orbital_velocity       1 non-null      float64
 12  habitable_zone_main_seq       1 non-null      int64
 13  spectral_type_AIII            1 non-null      float64
 14  spectral_type_AIV             1 non-null      float64
 15  spectral_type_AV              1 non-null      float64
 16  spectral_type_BIV             1 non-null      float64
 17  spectral_type_BV              1 non-null      float64
 18  spectral_type_FIV             1 non-null      float64
 19  spectral_type_FV              1 non-null      float64
 20  spectral_type_GII             1 non-null      float64
 21  spectral_type_GIII            1 non-null      float64
 22  spectral_type_GIV             1 non-null      float64
 23  spectral_type_GV              1 non-null      float64
 24  spectral_type_KII             1 non-null      float64
 25  spectral_type_KIII            1 non-null      float64
 26  spectral_type_KIV             1 non-null      float64
 27  spectral_type_KV              1 non-null      float64
 28  spectral_type_MIII            1 non-null      float64
 29  spectral_type_MV              1 non-null      float64
 30  spectral_type_SD              1 non-null      float64
 31  spectral_type_T               1 non-null      float64
 32  spectral_type_WD              1 non-null      float64
 33  spectral_type_sdB             1 non-null      float64
dtypes: float64(33), int64(1)
memory usage: 388.0+ bytes

#### Defining Weights for Key Features
Justification of Feature Weights for Earth-Analog Identification:

* **Highest Weights (7.0): Habitability-Critical Parameters:**
  * orbital_period_day = 7.0
  * habitable_zone_main_seq = 7.0
  * spectral_type_GV = 7.0
* These receive the strongest weighting because long-term habitability depends primarily on:
  * Stable orbital configuration
  * Location within the circumstellar habitable zone
  * Host star similarity to the Sun
* The concept of the circumstellar habitable zone originates from previous work on astrophyical analyis of habitable zones of main sequence stars demonstrates that surface liquid water stability is primarily governed by stellar flux and orbital distance.
* Solar-type stars such as Sun which have a spectral type GV (Star Type G Main Sequence V stars) provide:
  * Stable luminosity
  * Moderate UV radiation
  * Long main-sequence lifetimes
* The strong weight on spectral_type_GV reflects the hypothesis that true Earth analogs must orbit Sun-like main-sequence stars.
* The strong weight on habitable_zone_main_seq encodes this astrophysical constraint directly into the similarity metric.

* **High Weights (6.0): Radiative & Orbital Energy Balance:**
  * planet_equil_temp_k = 6.0
  * orbit_semi_major_axis_au = 6.0
* Equilibrium temperature describes planetary surface conditions and radiative balance
* Small deviations in orbital distance significantly alter stellar flux.
* The amount of stellar radiation (energy per unit area) a planet receives from its host star determines whether a planet is frozen, temperate, or in a runaway greenhouse state. Therefore, these parameters are weighted heavily.
* This aligns with classical habitable zone modeling and energy balance studies.

* **Moderate Weight (5.0): Planetary Radius:**
  * planet_rad_earth_rad = 5.0
* Radius is strongly correlated with bulk composition.
* Observational and theoretical work shows:
  * Planets which have a radii above about 1.5 Earth radii are likely Super-Earth Like while exoplanets beyond approximately 2 Earth radii are likely volatile-rich Neptune Like planets.
* Rocky composition probability declines sharply beyond that threshold.
* Thus radius is given substantial weight because Composition (rocky vs gaseous) is critical for Earth analog status.

* **Lower Weight (1.5): Stellar Mass and Radius Parameters:**
  * stellar_mass_solar_mass = 1.5
  * stellar_rad_solar_rad = 1.5
* Since the GV spectral type can range from G0v to G8v where the large the number indicates larger, brighter, and more massive Type G main sequence stars, applying a slight weight to the stellar mass and stellar radius ensure the planet's host star exhibit similar physical characteristics to the Sun which is G2V.
* Heavy weighting was not applied to avoid over-weighting since the equilibrium (average surface) planet temperature and habitable zone modeling already provides insight into these physical characteristics.

* **No Weight (1.0): Planetary Mass**
  * planet_mass_earth_mass = 1.0
* This may be surprising since Mass similarity is an important factor to consider.
* Mass is often more uncertain observationally since at larger distances, the ability to accurately observe, measure, and calculate the planet's mass becomes a challenge.
* So, many exoplanets lack precise mass measurements, so over-weighting mass could bias the ranking toward well-characterized systems rather than physically similar ones.
* However since Mass and radius are correlated. Radius alone already carries strong compositional information,

* **No Weight (1.0): Stellar Physical Parameters:**
  * stellar_surf_grav = 1.0
  * stellar_luminosity_solar_lum = 1.0
  * stellar_effective_temp_k = 1.0
* These are given baseline weights because their influence is already indirectly captured through equilibrum (average surface) planet temperature and habitable zone modeling.
* Over-weighting them would double-count stellar effects.

* **No Weight (1.0): All Other Non-GV Spectral Types:**
  * All non-GV spectral types = 1.0
* Avoid artificially penalizing potentially habitable Type K or Type M Main Sequence systems
* But still encode strong preference for solar analog systems via GV = 7.0
* This reflects a conservative astrophysical bias rather than excluding non-solar hosts outright.

In [ ]:
# Define weights (same order as columns)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 7.0,
    'orbit_semi_major_axis_au': 6.0,
    'planet_rad_earth_rad': 5.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 6.0,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.5,
    'stellar_mass_solar_mass': 1.5,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 7.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 7.0,
}

# Apply weights
new_exoplanets_filtered_KNN_weighted = new_exoplanets_filtered_KNN.copy()
earth_weighted = earth.copy()

for col in new_exoplanets_filtered_KNN_weighted.columns:
    weight = weights.get(col, 1.0)
    new_exoplanets_filtered_KNN_weighted[col] *= weight
    earth_weighted[col] *= weight

# This will turn the manhattan distance into a weighted manhattan distance and the euclidean distance into the weighted euclidean distance

### **Current KNN Model using Manhattan Distance (Proposed Method KNN Model #1)**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(new_exoplanets_filtered_KNN_weighted)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_weighted)

# Retrieve the 10 closest planet names
closest_planets_man = new_exoplanets_filtered_KNN.index[indices[0]].tolist()
closest_distances_man = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man[i]} (Distance: {closest_distances_man[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 10.1463)
2. Kepler-1638 b (Distance: 16.6309)
3. Kepler-51 e (Distance: 16.7816)
4. Kepler-1606 b (Distance: 19.2840)
5. Kepler-1701 b (Distance: 20.1409)
6. Kepler-22 b (Distance: 20.8885)
7. Kepler-1126 c (Distance: 22.4542)
8. Kepler-1549 b (Distance: 22.9228)
9. Kepler-1690 b (Distance: 23.2328)
10. Kepler-69 c (Distance: 23.5054)

The closest match to Earth in weighted feature space and thus, could exhibit a potential for habitabiltiy given its similarity to Earth and the Sun, is Kepler-452 b where its Manhattan distance was about 10.146 units away from Earth. The difference in the Manhattan distance of Kepler-452 b is substantal compared to all other top 10 exoplanets as the difference between Kepler-452 b and the second and third closest matches is approcimately 6.6 units.

Kepler-1638 b was the second closest match followed by kepler 51 e which is the third closest match with a difference in manhattan distances of about 16.631 and 16.782 respectively.

In [ ]:
all_distances, all_indices = nbrs.kneighbors(earth_weighted, n_neighbors=len(new_exoplanets_filtered_KNN_weighted))

# Map indices to names
all_planets = new_exoplanets_filtered_KNN_weighted.index[all_indices[0]]

# enter name of specifc planet to check its ranking
planet_to_check = 'Kepler-430 c'

# Find rank of Kepler-452 b
if planet_to_check in all_planets:
    rank = list(all_planets).index(planet_to_check) + 1
    distance = all_distances[0][rank-1]
    print(f"{planet_to_check} is ranked #{rank} overall with distance {distance:.4f}")
else:
    print(f"{planet_to_check} not found in dataset.")

Kepler-430 c is ranked #35 overall with distance 29.8656

In [ ]:
# df_weighted is already a DataFrame
df_imputed = new_exoplanets_filtered_KNN_weighted.copy()

# Extract Earth's feature vector correctly
earth_vector = earth_weighted.iloc[0]

# Pick the closest planet (rank 1)
closest_planet_man_name = closest_planets_man[0]
planet_vector = df_imputed.loc[closest_planet_man_name]

# Compute Manhattan feature contributions
feature_contributions = (planet_vector - earth_vector).abs()

# Sort by importance
feature_contributions = feature_contributions.sort_values(ascending=False)

print(F"The most Earth-Like planet is: {closest_planet_man_name}")
print("Feature contributions to Manhattan distance:")
print(feature_contributions)

The most Earth-Like planet is: Kepler-452 b
Feature contributions to Manhattan distance:
stellar_surf_grav               3.445550
planet_rad_earth_rad            3.150000
planet_mass_earth_mass          2.294107
planet_equil_temp_k             0.470588
orbital_period_day              0.375332
stellar_rad_solar_rad           0.148928
stellar_luminosity_solar_lum    0.134212
orbit_semi_major_axis_au        0.058400
stellar_mass_solar_mass         0.044500
stellar_effective_temp_k        0.014697
planet_orbital_velocity         0.009997
star_number_per_system          0.000000
habitable_zone_main_seq         0.000000
spectral_type_AIII              0.000000
spectral_type_AIV               0.000000
spectral_type_AV                0.000000
spectral_type_BIV               0.000000
spectral_type_BV                0.000000
spectral_type_FIV               0.000000
spectral_type_FV                0.000000
spectral_type_GII               0.000000
spectral_type_GIII              0.000000
spectral_type_GIV               0.000000
spectral_type_GV                0.000000
spectral_type_KII               0.000000
spectral_type_KIII              0.000000
spectral_type_KIV               0.000000
spectral_type_KV                0.000000
spectral_type_MIII              0.000000
spectral_type_MV                0.000000
spectral_type_SD                0.000000
spectral_type_T                 0.000000
spectral_type_WD                0.000000
spectral_type_sdB               0.000000
dtype: float64

When looking to see which feature differed the most for the most Earth-Like planet, the stellar surface gravity presented the greatest deviation though the difference is somewhat minimal. This is followed by the planet's radius and mass. This aligns with current observation since Kepler-452 b in Super-Earth Like in both mass and radius while its stellar surface gravity is slightly greater than that of the Sun's.

In [ ]:
# saving the rows associated with the top 10 earth like planets into a dataframe
closest_planets_man_list = new_exoplanets_filtered_KNN_weighted.loc[closest_planets_man]
closest_planets_man_list

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Kepler-452 b,1.0,7.375332,6.058400,8.150000,3.294107,5.529412,0.985303,1.648928,1.544500,4.445550,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1638 b,1.0,4.970071,4.704900,9.350000,4.605677,7.735294,0.994090,1.425000,1.376357,4.206098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-51 e,1.0,4.993714,4.725706,10.377172,4.600000,5.689555,0.983021,1.305000,1.440000,4.541055,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1606 b,1.0,3.764591,3.839040,10.420000,4.035577,6.795294,0.946188,1.239334,1.372500,4.543631,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1701 b,1.0,3.241357,3.409560,10.341552,3.978046,6.511765,0.909607,1.191304,1.300500,4.556486,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-22 b,1.0,5.555075,4.978971,10.955556,9.100000,6.215126,0.968311,1.321646,1.427812,4.478131,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1126 c,1.0,3.826492,3.840864,7.842500,2.999040,7.194118,1.010036,1.381459,1.349625,4.500237,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1549 b,1.0,4.118144,4.135500,13.073333,6.209992,6.376471,0.915127,1.327141,1.305600,4.487316,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1690 b,1.0,4.496655,4.288320,13.500910,6.601563,6.494118,0.964917,1.278222,1.348200,4.517811,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-69 c,1.0,4.646725,4.282463,9.207000,4.435693,6.887395,0.986869,1.423500,1.323750,4.377106,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### **Current K Nearest Neighbor Model using Euclidean Distance (Proposed Method KNN Model #2)**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(new_exoplanets_filtered_KNN_weighted)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_weighted)

# Retrieve the 10 closest planet names
closest_planets_euc = new_exoplanets_filtered_KNN.index[indices[0]].tolist()
closest_distances_euc = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc[i]} (Distance: {closest_distances_euc[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 5.2408)
2. Kepler-1638 b (Distance: 7.1452)
3. Kepler-51 e (Distance: 7.7652)
4. Kepler-1606 b (Distance: 8.2007)
5. Kepler-1701 b (Distance: 8.4660)
6. Kepler-1126 c (Distance: 9.4643)
7. Kepler-69 c (Distance: 9.9627)
8. Kepler-1185 b (Distance: 10.3500)
9. Kepler-442 b (Distance: 10.3699)
10. Kepler-311 d (Distance: 10.3847)

The closest match to Earth in weighted feature space and thus, could exhibit a potential for habitabiltiy given its similarity to Earth the Sun, is Kepler-452 b where its euclidean distance was about 5.241 units away from Earth. The difference in the euclidean distance of Kepler-452 b is relatively substantal compared to all other top 10 exoplanets as the difference between Kepler-452 b and the second closest match is about 2 units.

Kepler-1638 b, kepler 51 e, kepler-1606 b, and kepler-1701 b remained in their postions while kepler-22 b dropped from 6th place to 13th place. This is because The ranking of Earth-analog candidates varied depending on the distance metric. Manhattan distance prioritized planets with overall distributed similarity across features, whereas Euclidean distance penalized planets with large deviations in any single feature. Since Kepler-22 b had a larger mass of 9.1 times that of Earth's regardless of the overall similairty of all other features, the Euclidean distance penalized the larger deviation in mass.

In [ ]:
all_distances, all_indices = nbrs.kneighbors(earth_weighted, n_neighbors=len(new_exoplanets_filtered_KNN_weighted))

# Map indices to names
all_planets = new_exoplanets_filtered_KNN_weighted.index[all_indices[0]]

# enter name of specifc planet to check its ranking
planet_to_check = 'Kepler-22 b'

# Find rank of Kepler-452 b
if planet_to_check in all_planets:
    rank = list(all_planets).index(planet_to_check) + 1
    distance = all_distances[0][rank-1]
    print(f"{planet_to_check} is ranked #{rank} overall with distance {distance:.4f}")
else:
    print(f"{planet_to_check} not found in dataset.")

Kepler-22 b is ranked #13 overall with distance 10.7934

In [ ]:
# df_weighted is already a DataFrame
df_imputed = new_exoplanets_filtered_KNN_weighted.copy()

# Extract Earth's feature vector correctly
earth_vector = earth_weighted.iloc[0]

# Pick the closest planet (rank 1)
closest_planet_euc_name = closest_planets_euc[0]
planet_vector = df_imputed.loc[closest_planet_euc_name]

# Compute squared differences (Euclidean contributions before sqrt)
feature_contributions = (planet_vector - earth_vector) ** 2

# Sort by importance
feature_contributions = feature_contributions.sort_values(ascending=False)

print(F"The most Earth-Like planet is: {closest_planet_euc_name}")
print("Feature contributions to Euclidean distance (squared terms):")
print(feature_contributions)

The most Earth-Like planet is: Kepler-452 b
Feature contributions to Euclidean distance (squared terms):
stellar_surf_grav               11.871815
planet_rad_earth_rad             9.922500
planet_mass_earth_mass           5.262929
planet_equil_temp_k              0.221453
orbital_period_day               0.140874
stellar_rad_solar_rad            0.022179
stellar_luminosity_solar_lum     0.018013
orbit_semi_major_axis_au         0.003411
stellar_mass_solar_mass          0.001980
stellar_effective_temp_k         0.000216
planet_orbital_velocity          0.000100
star_number_per_system           0.000000
habitable_zone_main_seq          0.000000
spectral_type_AIII               0.000000
spectral_type_AIV                0.000000
spectral_type_AV                 0.000000
spectral_type_BIV                0.000000
spectral_type_BV                 0.000000
spectral_type_FIV                0.000000
spectral_type_FV                 0.000000
spectral_type_GII                0.000000
spectral_type_GIII               0.000000
spectral_type_GIV                0.000000
spectral_type_GV                 0.000000
spectral_type_KII                0.000000
spectral_type_KIII               0.000000
spectral_type_KIV                0.000000
spectral_type_KV                 0.000000
spectral_type_MIII               0.000000
spectral_type_MV                 0.000000
spectral_type_SD                 0.000000
spectral_type_T                  0.000000
spectral_type_WD                 0.000000
spectral_type_sdB                0.000000
dtype: float64

When looking to see which feature differed the most for the most Earth-Like planet, there is a similar trend to that of the manhattan distance KNN model. However, this time the difference appears to be substantially larger primarily for the stellar surface gravity followed by the planet's radius and mass. This value is expected given that the euclidean distance penalizes large deviations.

In [ ]:
# saving the rows associated with the top 10 earth like planets into a dataframe
closest_planets_euc_list = new_exoplanets_filtered_KNN_weighted.loc[closest_planets_euc]
closest_planets_euc_list

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Kepler-452 b,1.0,7.375332,6.058400,8.150000,3.294107,5.529412,0.985303,1.648928,1.544500,4.445550,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1638 b,1.0,4.970071,4.704900,9.350000,4.605677,7.735294,0.994090,1.425000,1.376357,4.206098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-51 e,1.0,4.993714,4.725706,10.377172,4.600000,5.689555,0.983021,1.305000,1.440000,4.541055,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1606 b,1.0,3.764591,3.839040,10.420000,4.035577,6.795294,0.946188,1.239334,1.372500,4.543631,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1701 b,1.0,3.241357,3.409560,10.341552,3.978046,6.511765,0.909607,1.191304,1.300500,4.556486,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1126 c,1.0,3.826492,3.840864,7.842500,2.999040,7.194118,1.010036,1.381459,1.349625,4.500237,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-69 c,1.0,4.646725,4.282463,9.207000,4.435693,6.887395,0.986869,1.423500,1.323750,4.377106,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1185 b,1.0,1.999842,2.629400,6.650000,1.448796,8.603922,0.994233,1.378000,1.560600,4.422290,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-442 b,1.0,2.152254,2.370480,7.360714,1.653236,6.005882,0.781393,0.946794,0.969600,4.663674,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-311 d,1.0,4.447112,4.401345,10.259000,3.917929,7.521569,1.020392,1.725500,1.464600,4.320136,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

---
#### **Interpretation of All Results from KNN Models**
Although the top 5 Earth-Like exoplanets remained identical across both weighted Manhattan and weighted Euclidean distance metrics, three planets within the top twenty differed between the two rankings. This indicates that while the strongest Earth analogs are robust to metric choice, mid-tier candidates (ranks 6–10) are sensitive to how feature deviations are aggregated. There is particuarly increased sensitivity to metric choice in regions of feature space where similarity is less tightly constrained.

The stability of the top five candidates across both metrics suggests that the highest-ranked candidates form a robust well-defined similarity cluster in weighted feature space, while lower-ranked candidates occupy a transitional region where similarity is less tightly constrained and more dependent on metric formulation.

The difference in results between the two distance metrics indicate that the manhattan distance with the KNN Model is better suited to understand how similar each feature combimed compares to Earth. While the euclidean distance with the KNN Model is better suited to understand how similar each feature is to Earth while minimizing as many deviations possible. Therefore, rather than identifying a single superior metric, the comparison highlights complementary perspectives on planetary similarity.

-----

# **Experiment #1: Baseline Ranking Comparison**
The purpose of this experiment is to show that our proposed weighted Earth-like similarity ranking provides more meaningful results than simpler ranking approaches.

Please compare your current weighted ranking method with a few simpler baseline methods using the same final cleaned dataset and the same Earth reference row.

### Preparing Dataset for Experiment #1 Unweighted Baseline KNN Models #3 and #4

In [ ]:
# copy dataset for experiment #1 for unweighted baseline KNN Models #3 and #4
experiment_1_baseline = new_exoplanets_filtered4.copy()
experiment_1_baseline

,planet_name,star_number_per_system,spectral_type,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
0,11 Com b,2.0,GIII,324.620000,1.226000,61.636581,5505.066162,653.137165,4808.000000,13.760000,2.090000,2.380000,90.778824,1.305879,0
1,11 UMi b,1.0,KIII,516.219985,1.526667,57.057421,4684.814200,728.367922,4276.500000,26.935000,2.780000,1.765000,217.709668,1.349663,0
2,14 And b,1.0,KIII,186.300000,0.761667,30.026230,1224.550434,756.725320,4850.500000,11.275000,1.780000,2.590000,63.134826,1.528982,0
3,14 Her b,1.0,KV,1766.378417,2.814750,42.726171,2559.472162,127.963437,5296.985000,0.999085,0.904000,4.418006,0.705033,0.566812,0
4,16 Cyg B b,3.0,GV,799.375000,1.662833,20.176910,533.514528,191.413504,5728.594000,1.129135,1.016599,4.342293,1.231895,0.782034,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5414,ups And b,2.0,FV,4.616229,0.058895,13.205018,219.960419,1303.179545,6137.820000,1.614742,1.276049,4.161529,3.320113,4.655553,0
5415,ups And c,2.0,FV,240.728533,0.827712,21.840560,629.595000,346.443928,6117.093333,1.614742,1.301399,4.148705,3.275493,1.254124,0
5416,ups And d,2.0,FV,1285.346167,2.528382,31.047562,1313.220000,198.221771,6117.093333,1.614742,1.301399,4.148705,3.275493,0.717561,0
5417,ups Leo b,1.0,GIII,385.200000,1.180000,11.410451,162.092488,604.668957,4836.000000,11.220000,1.480000,2.460000,61.776135,1.120121,0
5418,xi Aql b,1.0,KIII,136.860000,0.628333,21.628811,616.904938,831.944281,4810.500000,11.430000,1.740000,2.635000,62.768708,1.664388,0

### Ensure all features are normalized in terms of Earth

In [ ]:
# Normalize the orbital period column
experiment_1_baseline['orbital_period_day'] = experiment_1_baseline['orbital_period_day'] / 365.26

# Normalize the planet equilibrium temperature
experiment_1_baseline['planet_equil_temp_k'] = experiment_1_baseline['planet_equil_temp_k'] / 255.0

# Normalize the stellar effective temperature
experiment_1_baseline['stellar_effective_temp_k'] = experiment_1_baseline['stellar_effective_temp_k'] / 5772.0

### Creating target row for Earth

In [ ]:
# creating a target row called Earth which all the other rows will be compared to (similarity search)
earth = pd.DataFrame({'planet_name': ['Earth'],
                      'star_number_per_system': [1.0],
                      'orbital_period_day': [1.0],
                      'orbit_semi_major_axis_au':[1.0],
                      'planet_rad_earth_rad': [1.0],
                      'planet_mass_earth_mass': [1.0],
                      'planet_equil_temp_k': [1.0],
                      'spectral_type': ['GV'],
                      'stellar_effective_temp_k': [1.0],
                      'stellar_rad_solar_rad': [1.0],
                      'stellar_mass_solar_mass': [1.0],
                      'stellar_surf_grav': [1.0],
                      'stellar_luminosity_solar_lum': [1.0],
                      'planet_orbital_velocity': [1.0],
                      'habitable_zone_main_seq': [1]})

### Setting planet name as the index (since planet name is the observation)

In [ ]:
# set planet name as index for earth row
earth.set_index('planet_name', inplace=True)

# setting the planet_name as the index
experiment_1_baseline.set_index('planet_name', inplace=True)

### Encoding Categorical Columns

In [ ]:
# Combine both for fitting the OneHotEncoder to prevent unseen label errors
combined_spectral_type = pd.concat([experiment_1_baseline['spectral_type'], earth['spectral_type']], ignore_index=True)

# Ensure combined_spectral_type is a DataFrame with 1 column
combined_spectral_type_df = pd.DataFrame(combined_spectral_type, columns=['spectral_type'])

# Fit the OneHotEncoder for categorical columns
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoder.fit(combined_spectral_type_df)

# Transform both the original cleaned dataset and the earth target row dataset
experiment_1_baseline_encoded = encoder.transform(experiment_1_baseline[['spectral_type']])
earth_encoded = encoder.transform(earth[['spectral_type']])

# Generate column names for the encoded columns
encoded_columns = encoder.get_feature_names_out(['spectral_type'])

# Convert to DataFrame and ensure indices match
experiment_1_baseline_encoded = pd.DataFrame(
    experiment_1_baseline_encoded,
    columns=encoded_columns,
    index=experiment_1_baseline.index
)
earth_encoded = pd.DataFrame(
    earth_encoded,
    columns=encoded_columns,
    index=earth.index
)

# Drop orignal spectral_type column since we have generated encoded columns
experiment_1_baseline = experiment_1_baseline.drop(columns=['spectral_type'])
earth = earth.drop(columns=['spectral_type'])

# Add encoded columns back into original cleaned dataset and earth
experiment_1_baseline = pd.concat([experiment_1_baseline, experiment_1_baseline_encoded], axis=1)
earth = pd.concat([earth, earth_encoded], axis=1)

In [ ]:
experiment_1_baseline.head()

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
earth.head()

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# copy of dataset for experiment #3
experiment_3 = experiment_1_baseline.copy()
experiment_3

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups Leo b,1.0,1.054591,1.180000,11.410451,162.092488,2.371251,0.837838,11.220000,1.480000,2.460000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xi Aql b,1.0,0.374692,0.628333,21.628811,616.904938,3.262527,0.833420,11.430000,1.740000,2.635000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# copy of earth dataset for experiment #3
earth_3 = earth.copy()
earth_3

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### No weights applied

In [ ]:
# no weights applied (all weights = 1.0)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.0,
    'stellar_mass_solar_mass': 1.0,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 1.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights (note: all weights = 1.0)
for col in experiment_1_baseline.columns:
    weight = weights.get(col, 1.0)
    experiment_1_baseline[col] *= weight
    earth[col] *= weight

In [ ]:
experiment_1_baseline.head()

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
earth.head()

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## **Experiment #1 Baseline Unweighted KNN Manhattan Distance Model #3**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_1_baseline)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth)

# Retrieve the 10 closest planet names
closest_planets_man2 = experiment_1_baseline.index[indices[0]].tolist()
closest_distances_man2 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man2[i]} (Distance: {closest_distances_man2[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.7993)
2. Kepler-1185 b (Distance: 7.7585)
3. Kepler-132 e (Distance: 8.4888)
4. Kepler-1126 c (Distance: 8.5760)
5. Kepler-384 c (Distance: 8.7051)
6. Kepler-1638 b (Distance: 8.8194)
7. Kepler-1253 b (Distance: 8.8426)
8. Kepler-1965 b (Distance: 8.9975)
9. Kepler-1440 b (Distance: 9.0092)
10. Kepler-1605 b (Distance: 9.0991)

## **Experiment #1 Baseline Unweighted KNN Euclidean Distance Model #4**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_1_baseline)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth)

# Retrieve the 10 closest planet names
closest_planets_euc2 = experiment_1_baseline.index[indices[0]].tolist()
closest_distances_euc2 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc2[i]} (Distance: {closest_distances_euc2[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.7907)
2. Kepler-1253 b (Distance: 3.8157)
3. Kepler-132 e (Distance: 3.8466)
4. Kepler-384 c (Distance: 3.8933)
5. Kepler-130 d (Distance: 3.9603)
6. Kepler-1440 b (Distance: 3.9850)
7. Kepler-1498 b (Distance: 3.9960)
8. Kepler-1441 b (Distance: 4.0444)
9. Kepler-1965 b (Distance: 4.1045)
10. Kepler-1620 b (Distance: 4.1106)

In [ ]:
# seeing where kepler-452 b is ranked for Baseline Unweighted KNN Euclidean Distance Model #4
all_distances, all_indices = nbrs.kneighbors(earth, n_neighbors=len(experiment_1_baseline))

# Map indices to names
all_planets = experiment_1_baseline.index[all_indices[0]]

# enter name of specifc planet to check its ranking
planet_to_check = 'Kepler-452 b'

# Find rank of Kepler-452 b
if planet_to_check in all_planets:
    rank = list(all_planets).index(planet_to_check) + 1
    distance = all_distances[0][rank-1]
    print(f"{planet_to_check} is ranked #{rank} overall with distance {distance:.4f}")
else:
    print(f"{planet_to_check} not found in dataset.")

Kepler-452 b is ranked #15 overall with distance 4.1916

In [ ]:
# viewing the row for kepler-452 b
experiment_1_baseline.loc['Kepler-452 b']

star_number_per_system          1.000000
orbital_period_day              1.053619
orbit_semi_major_axis_au        1.009733
planet_rad_earth_rad            1.630000
planet_mass_earth_mass          3.294107
planet_equil_temp_k             0.921569
stellar_effective_temp_k        0.985303
stellar_rad_solar_rad           1.099285
stellar_mass_solar_mass         1.029667
stellar_surf_grav               4.445550
stellar_luminosity_solar_lum    1.134212
planet_orbital_velocity         1.009997
habitable_zone_main_seq         1.000000
spectral_type_AIII              0.000000
spectral_type_AIV               0.000000
spectral_type_AV                0.000000
spectral_type_BIV               0.000000
spectral_type_BV                0.000000
spectral_type_FIV               0.000000
spectral_type_FV                0.000000
spectral_type_GII               0.000000
spectral_type_GIII              0.000000
spectral_type_GIV               0.000000
spectral_type_GV                1.000000
spectral_type_KII               0.000000
spectral_type_KIII              0.000000
spectral_type_KIV               0.000000
spectral_type_KV                0.000000
spectral_type_MIII              0.000000
spectral_type_MV                0.000000
spectral_type_SD                0.000000
spectral_type_T                 0.000000
spectral_type_WD                0.000000
spectral_type_sdB               0.000000
Name: Kepler-452 b, dtype: float64

In [ ]:
experiment_1_baseline.loc['Kepler-1185 b']

star_number_per_system          1.000000
orbital_period_day              0.285692
orbit_semi_major_axis_au        0.438233
planet_rad_earth_rad            1.330000
planet_mass_earth_mass          1.448796
planet_equil_temp_k             1.433987
stellar_effective_temp_k        0.994233
stellar_rad_solar_rad           0.918667
stellar_mass_solar_mass         1.040400
stellar_surf_grav               4.422290
stellar_luminosity_solar_lum    0.821229
planet_orbital_velocity         1.541070
habitable_zone_main_seq         0.000000
spectral_type_AIII              0.000000
spectral_type_AIV               0.000000
spectral_type_AV                0.000000
spectral_type_BIV               0.000000
spectral_type_BV                0.000000
spectral_type_FIV               0.000000
spectral_type_FV                0.000000
spectral_type_GII               0.000000
spectral_type_GIII              0.000000
spectral_type_GIV               0.000000
spectral_type_GV                1.000000
spectral_type_KII               0.000000
spectral_type_KIII              0.000000
spectral_type_KIV               0.000000
spectral_type_KV                0.000000
spectral_type_MIII              0.000000
spectral_type_MV                0.000000
spectral_type_SD                0.000000
spectral_type_T                 0.000000
spectral_type_WD                0.000000
spectral_type_sdB               0.000000
Name: Kepler-1185 b, dtype: float64

### Preparing Dataset for Experiment #1 Unweighted Baseline Habitable Zone Filtering KNN Models #5 and #6

In [ ]:
# copy dataset for experiment #1 for unweighted baseline Habitable Zone filtering KNN Model #5
experiment_1_baseline_habitable_zone = experiment_1_baseline.copy()
experiment_1_baseline_habitable_zone

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups Leo b,1.0,1.054591,1.180000,11.410451,162.092488,2.371251,0.837838,11.220000,1.480000,2.460000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xi Aql b,1.0,0.374692,0.628333,21.628811,616.904938,3.262527,0.833420,11.430000,1.740000,2.635000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# fitlering dataset for rows where only habitable zone = 1
experiment_1_baseline_habitable_zone = experiment_1_baseline_habitable_zone[experiment_1_baseline_habitable_zone['habitable_zone_main_seq'] == 1]
experiment_1_baseline_habitable_zone

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
55 Cnc f,2.0,0.713961,0.781513,6.344191,47.529849,0.925168,0.908026,0.963067,0.924286,4.412356,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AU Mic e,1.0,0.091031,0.170681,4.301580,21.100000,1.277392,0.634962,0.820000,0.600000,4.520000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
BD+49 828 b,1.0,7.090839,4.200000,19.718599,508.500000,1.057325,0.856376,7.600000,1.520000,2.850000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
BD-11 4672 c,1.0,0.203143,0.300000,3.696464,15.370000,1.055934,0.788288,0.639000,0.651000,4.642000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
EPIC 212737443 c,1.0,0.179461,0.280000,2.690000,6.554346,1.239216,0.811504,0.673000,0.690000,4.622000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TOI-4633 c,2.0,0.744523,0.847000,3.200000,123.000000,1.026873,1.004851,1.050000,1.100000,4.436836,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TOI-500 e,1.0,0.167826,0.275206,3.659440,15.050000,1.108166,0.769231,0.678000,0.740000,4.618000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
TOI-544 c,1.0,0.137132,0.228093,4.340406,21.500000,1.095610,0.722280,0.623000,0.631000,4.680000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
TOI-712 d,1.0,0.232272,0.340500,2.474000,5.590613,1.229804,0.800762,0.674000,0.732000,4.645000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
WASP-41 c,1.0,1.152604,1.070000,27.391649,1010.699400,0.945098,0.960672,0.870000,0.930000,4.530000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# removing all features except planets radius, planet mass, orbital semi major axis, and planet equilibrium temeprature for experiment_1_baseline_habitable_zone dataframe
experiment_1_baseline_habitable_zone = experiment_1_baseline_habitable_zone[['planet_rad_earth_rad', 'planet_mass_earth_mass', 'orbit_semi_major_axis_au', 'planet_equil_temp_k']]
experiment_1_baseline_habitable_zone

,planet_rad_earth_rad,planet_mass_earth_mass,orbit_semi_major_axis_au,planet_equil_temp_k
planet_name,,,,
55 Cnc f,6.344191,47.529849,0.781513,0.925168
AU Mic e,4.301580,21.100000,0.170681,1.277392
BD+49 828 b,19.718599,508.500000,4.200000,1.057325
BD-11 4672 c,3.696464,15.370000,0.300000,1.055934
EPIC 212737443 c,2.690000,6.554346,0.280000,1.239216
...,...,...,...,...
TOI-4633 c,3.200000,123.000000,0.847000,1.026873
TOI-500 e,3.659440,15.050000,0.275206,1.108166
TOI-544 c,4.340406,21.500000,0.228093,1.095610
TOI-712 d,2.474000,5.590613,0.340500,1.229804
WASP-41 c,27.391649,1010.699400,1.070000,0.945098

In [ ]:
# removing all features except planets radius, planet mass, orbital semi major axis, and planet equilibrium temeprature for earth dataframe
earth_habitable_zone = earth[['planet_rad_earth_rad', 'planet_mass_earth_mass', 'orbit_semi_major_axis_au', 'planet_equil_temp_k']]
earth_habitable_zone

,planet_rad_earth_rad,planet_mass_earth_mass,orbit_semi_major_axis_au,planet_equil_temp_k
planet_name,,,,
Earth,1.0,1.0,1.0,1.0

## **Experiment #1 Baseline Unweighted Baseline Habitable Zone Filtering Manhattan Distance KNN Model #5**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_1_baseline_habitable_zone)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_habitable_zone)

# Retrieve the 10 closest planet names
closest_planets_man3 = experiment_1_baseline_habitable_zone.index[indices[0]].tolist()
closest_distances_man3 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man3[i]} (Distance: {closest_distances_man3[i]:.4f})")

Top 10 most similar planets:
1. Kepler-438 b (Distance: 0.9746)
2. Kepler-296 e (Distance: 1.7012)
3. Kepler-442 b (Distance: 1.7313)
4. Kepler-395 c (Distance: 1.7369)
5. Kepler-138 e (Distance: 1.8670)
6. Kepler-452 b (Distance: 3.0123)
7. Kepler-1410 b (Distance: 3.6892)
8. Kepler-1544 b (Distance: 4.2228)
9. Kepler-1701 b (Distance: 4.5634)
10. Kepler-1606 b (Distance: 4.6123)

## **Experiment #1 Baseline Unweighted Baseline Habitable Zone Filtering Euclidean Distance KNN Model #6**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_1_baseline_habitable_zone)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_habitable_zone)

# Retrieve the 10 closest planet names
closest_planets_euc3 = experiment_1_baseline_habitable_zone.index[indices[0]].tolist()
closest_distances_euc3 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc3[i]} (Distance: {closest_distances_euc3[i]:.4f})")

Top 10 most similar planets:
1. Kepler-438 b (Distance: 0.8386)
2. Kepler-442 b (Distance: 1.0078)
3. Kepler-395 c (Distance: 1.0078)
4. Kepler-296 e (Distance: 1.0208)
5. Kepler-138 e (Distance: 1.0622)
6. Kepler-452 b (Distance: 2.3804)
7. Kepler-1410 b (Distance: 2.4949)
8. Kepler-1544 b (Distance: 3.1276)
9. Kepler-1701 b (Distance: 3.1943)
10. Kepler-1450 b (Distance: 3.2306)

----------------

# **Experiment #2: Ablation Study**
After the baseline comparison, please perform an ablation study. The purpose of this experiment is to identify which feature groups are most important for the Earth-like ranking.

In this experiment, you will run the same ranking method multiple times, but each time you will remove one group of features and observe how the top 10 rankings change.

Please use the current weighted Manhattan and weighted Euclidean ranking methods as the full model.

## **Experiment #2 Ablation KNN Model (Full Model) #7 and #8**

In [ ]:
# already complete

### Preparing Dataset for Experiment #2 Ablation (No planetary features) KNN Models #9 and #10

In [ ]:
# creating copy of experiment_1_baseline dataset
experiment_2_ablation = experiment_1_baseline.copy()
experiment_2_ablation

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups Leo b,1.0,1.054591,1.180000,11.410451,162.092488,2.371251,0.837838,11.220000,1.480000,2.460000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xi Aql b,1.0,0.374692,0.628333,21.628811,616.904938,3.262527,0.833420,11.430000,1.740000,2.635000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# removing all planetary features from the experiment_2_ablation dataframe
experiment_2_ablation_no_planet = experiment_2_ablation.drop(columns=['planet_rad_earth_rad', 'planet_mass_earth_mass',
                                                                      'orbit_semi_major_axis_au', 'planet_equil_temp_k', 'planet_orbital_velocity'])
experiment_2_ablation_no_planet

,star_number_per_system,orbital_period_day,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,habitable_zone_main_seq,spectral_type_AIII,spectral_type_AIV,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,0.832987,13.760000,2.090000,2.380000,90.778824,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,0.740904,26.935000,2.780000,1.765000,217.709668,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.840350,11.275000,1.780000,2.590000,63.134826,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,0.917704,0.999085,0.904000,4.418006,0.705033,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,0.992480,1.129135,1.016599,4.342293,1.231895,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,1.063378,1.614742,1.276049,4.161529,3.320113,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,1.059787,1.614742,1.301399,4.148705,3.275493,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,1.059787,1.614742,1.301399,4.148705,3.275493,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups Leo b,1.0,1.054591,0.837838,11.220000,1.480000,2.460000,61.776135,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xi Aql b,1.0,0.374692,0.833420,11.430000,1.740000,2.635000,62.768708,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# removing all planetary features from earth dataframe
earth_no_planet = earth.drop(columns=['planet_rad_earth_rad', 'planet_mass_earth_mass', 'orbit_semi_major_axis_au', 'planet_equil_temp_k', 'planet_orbital_velocity'])
earth_no_planet

,star_number_per_system,orbital_period_day,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,habitable_zone_main_seq,spectral_type_AIII,spectral_type_AIV,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## **Experiment #2 Ablation (No planetary features) Manhattan Distance KNN Model #9**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_planet)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_planet)

# Retrieve the 10 closest planet names
closest_planets_man4 = experiment_2_ablation_no_planet.index[indices[0]].tolist()
closest_distances_man4 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man4[i]} (Distance: {closest_distances_man4[i]:.4f})")

Top 10 most similar planets:
1. HD 43197 b (Distance: 3.6984)
2. Kepler-1638 b (Distance: 3.7567)
3. Kepler-452 b (Distance: 3.7770)
4. Kepler-289 e (Distance: 3.7783)
5. Kepler-1625 b (Distance: 3.8063)
6. PH2 b (Distance: 3.8435)
7. Kepler-1634 b (Distance: 3.8917)
8. Kepler-1636 b (Distance: 3.9035)
9. HD 142415 b (Distance: 3.9222)
10. Kepler-1519 b (Distance: 3.9488)

## **Experiment #2 Ablation (No planetary features) Euclidean Distance KNN Model #10**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_planet)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_planet)

# Retrieve the 10 closest planet names
closest_planets_euc4 = experiment_2_ablation_no_planet.index[indices[0]].tolist()
closest_distances_euc4 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc4[i]} (Distance: {closest_distances_euc4[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1625 b (Distance: 3.2208)
2. Kepler-1638 b (Distance: 3.2230)
3. Kepler-784 b (Distance: 3.2285)
4. Kepler-1570 b (Distance: 3.2712)
5. Kepler-1929 b (Distance: 3.2985)
6. Kepler-525 b (Distance: 3.3029)
7. Kepler-638 b (Distance: 3.3036)
8. HD 43197 b (Distance: 3.3176)
9. HD 44219 b (Distance: 3.3178)
10. Kepler-806 b (Distance: 3.3239)

### Preparing Dataset for Experiment #2 Ablation (No stellar features - Partial) KNN Models #11 and #12

In [ ]:
# removing all stellar features except for spectral type from the experiment_2_ablation dataframe
experiment_2_ablation_no_stellar = experiment_2_ablation.drop(columns=['stellar_effective_temp_k', 'stellar_rad_solar_rad', 'stellar_mass_solar_mass',
                                                                       'stellar_surf_grav', 'stellar_luminosity_solar_lum'])
experiment_2_ablation_no_stellar

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,planet_orbital_velocity,habitable_zone_main_seq,spectral_type_AIII,spectral_type_AIV,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,1.305879,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,1.349663,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,1.528982,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.566812,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.782034,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,4.655553,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.254124,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,0.717561,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups Leo b,1.0,1.054591,1.180000,11.410451,162.092488,2.371251,1.120121,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xi Aql b,1.0,0.374692,0.628333,21.628811,616.904938,3.262527,1.664388,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# removing all stellar features except for spectral type from earth dataframe
earth_no_stellar = earth.drop(columns=['stellar_effective_temp_k', 'stellar_rad_solar_rad', 'stellar_mass_solar_mass',
                                                                       'stellar_surf_grav', 'stellar_luminosity_solar_lum'])
earth_no_stellar

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,planet_orbital_velocity,habitable_zone_main_seq,spectral_type_AIII,spectral_type_AIV,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## **Experiment #2 Ablation (No Stellar features - Partial) Manhattan Distance KNN Model #11**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_stellar)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_stellar)

# Retrieve the 10 closest planet names
closest_planets_man5 = experiment_2_ablation_no_stellar.index[indices[0]].tolist()
closest_distances_man5 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man5[i]} (Distance: {closest_distances_man5[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 3.0759)
2. Kepler-1185 b (Distance: 4.0299)
3. Kepler-1605 b (Distance: 4.5805)
4. Kepler-442 b (Distance: 4.7031)
5. Kepler-438 b (Distance: 4.7050)
6. Kepler-132 e (Distance: 4.7608)
7. Kepler-1126 c (Distance: 4.7655)
8. Kepler-384 c (Distance: 4.9006)
9. Kepler-1965 b (Distance: 4.9600)
10. Kepler-186 f (Distance: 5.0085)

## **Experiment #2 Ablation (No Stellar features - Partial) Euclidean Distance KNN Model #12**

In [ ]:
#Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_stellar)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_stellar)

# Retrieve the 10 closest planet names
closest_planets_euc5 = experiment_2_ablation_no_stellar.index[indices[0]].tolist()
closest_distances_euc5 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc5[i]} (Distance: {closest_distances_euc5[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 1.6178)
2. Kepler-132 e (Distance: 1.8632)
3. Kepler-442 b (Distance: 1.8903)
4. Kepler-186 f (Distance: 1.9865)
5. Kepler-1253 b (Distance: 1.9978)
6. Kepler-1498 b (Distance: 2.0314)
7. Kepler-438 b (Distance: 2.0502)
8. Kepler-384 c (Distance: 2.0774)
9. Kepler-1965 b (Distance: 2.0815)
10. Kepler-138 e (Distance: 2.1101)

### Preparing Dataset for Experiment #2 Ablation (No stellar features - Full) KNN Models #11.5 and #12.5

In [ ]:
# removing all stellar features including one hot encoded spctral type features from the experiment_2_ablation dataframe
# so removing the spctral type features from experiment_2_ablation_no_stellar
experiment_2_ablation_no_stellar_full = experiment_2_ablation_no_stellar.drop(columns=[col for col in experiment_2_ablation_no_stellar.columns if col.startswith('spectral_type_')])
experiment_2_ablation_no_stellar_full

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,planet_orbital_velocity,habitable_zone_main_seq
planet_name,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,1.305879,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,1.349663,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,1.528982,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.566812,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.782034,0.0
...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,4.655553,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.254124,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,0.717561,0.0
ups Leo b,1.0,1.054591,1.180000,11.410451,162.092488,2.371251,1.120121,0.0
xi Aql b,1.0,0.374692,0.628333,21.628811,616.904938,3.262527,1.664388,0.0

In [ ]:
# removing all stellar features including one hot encoded spctral type features from the earth dataframe
# so removing the spctral type features from earth_no_stellar
earth_no_stellar_full = earth_no_stellar.drop(columns=[col for col in earth_no_stellar.columns if col.startswith('spectral_type_')])
earth_no_stellar_full

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,planet_orbital_velocity,habitable_zone_main_seq
planet_name,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

## **Experiment #2 Ablation (No Stellar features - Full) Manhattan Distance KNN Model #11.5**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_stellar_full)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_stellar_full)

# Retrieve the 10 closest planet names
closest_planets_man5_5 = experiment_2_ablation_no_stellar_full.index[indices[0]].tolist()
closest_distances_man5_5 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man5_5[i]} (Distance: {closest_distances_man5_5[i]:.4f})")

Top 10 most similar planets:
1. Kepler-442 b (Distance: 2.7031)
2. Kepler-438 b (Distance: 2.7050)
3. Kepler-186 f (Distance: 3.0085)
4. Kepler-452 b (Distance: 3.0759)
5. Kepler-138 e (Distance: 3.4852)
6. Kepler-395 c (Distance: 3.5338)
7. Teegarden's Star d (Distance: 3.6040)
8. Teegarden's Star c (Distance: 3.6612)
9. TOI-700 e (Distance: 3.6827)
10. TOI-700 d (Distance: 3.6995)

## **Experiment #2 Ablation (No Stellar features - Full) Euclidean Distance KNN Model #12.5**

In [ ]:
#Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_stellar_full)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_stellar_full)

# Retrieve the 10 closest planet names
closest_planets_euc5_5 = experiment_2_ablation_no_stellar_full.index[indices[0]].tolist()
closest_distances_euc5_5 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc5_5[i]} (Distance: {closest_distances_euc5_5[i]:.4f})")

Top 10 most similar planets:
1. Kepler-442 b (Distance: 1.2543)
2. Kepler-186 f (Distance: 1.3951)
3. Kepler-438 b (Distance: 1.4844)
4. Kepler-138 e (Distance: 1.5660)
5. Kepler-1185 b (Distance: 1.6178)
6. Kepler-395 c (Distance: 1.6217)
7. Kepler-1229 b (Distance: 1.6636)
8. Teegarden's Star d (Distance: 1.7041)
9. TOI-700 d (Distance: 1.7071)
10. GJ 1002 c (Distance: 1.7488)

### Preparing Dataset for Experiment #2 Ablation (No orbital features) KNN Models #13 and #14

In [ ]:
# removing all orbital features from the experiment_2_ablation dataframe
experiment_2_ablation_no_orbital = experiment_2_ablation.drop(columns=['orbital_period_day', 'orbit_semi_major_axis_au'])
experiment_2_ablation_no_orbital

,star_number_per_system,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,90.778824,1.305879,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,217.709668,1.349663,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,63.134826,1.528982,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,0.705033,0.566812,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,1.231895,0.782034,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,3.320113,4.655553,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,3.275493,1.254124,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,3.275493,0.717561,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups Leo b,1.0,11.410451,162.092488,2.371251,0.837838,11.220000,1.480000,2.460000,61.776135,1.120121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xi Aql b,1.0,21.628811,616.904938,3.262527,0.833420,11.430000,1.740000,2.635000,62.768708,1.664388,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# removing all orbital features from the earth dataframe
earth_no_orbital = earth.drop(columns=['orbital_period_day', 'orbit_semi_major_axis_au'])
earth_no_orbital

,star_number_per_system,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## **Experiment #2 Ablation (No Orbital features) Manhattan Distance KNN Model #13**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_orbital)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_orbital)

# Retrieve the 10 closest planet names
closest_planets_man6 = experiment_2_ablation_no_orbital.index[indices[0]].tolist()
closest_distances_man6 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man6[i]} (Distance: {closest_distances_man6[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 6.4824)
2. Kepler-452 b (Distance: 6.7359)
3. Kepler-384 c (Distance: 7.0647)
4. Kepler-132 e (Distance: 7.2291)
5. Kepler-1965 b (Distance: 7.3424)
6. Kepler-1440 b (Distance: 7.3452)
7. Kepler-1253 b (Distance: 7.3458)
8. Kepler-1505 b (Distance: 7.6164)
9. Kepler-1498 b (Distance: 7.7329)
10. Kepler-1441 b (Distance: 7.7526)

## **Experiment #2 Ablation (No Orbital features) Euclidean Distance KNN Model #14**

In [ ]:
#Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_orbital)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_orbital)

# Retrieve the 10 closest planet names
closest_planets_euc6 = experiment_2_ablation_no_orbital.index[indices[0]].tolist()
closest_distances_euc6 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc6[i]} (Distance: {closest_distances_euc6[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1253 b (Distance: 3.6649)
2. Kepler-1185 b (Distance: 3.6802)
3. Kepler-384 c (Distance: 3.7157)
4. Kepler-132 e (Distance: 3.7408)
5. Kepler-1440 b (Distance: 3.8064)
6. Kepler-1498 b (Distance: 3.8268)
7. Kepler-130 d (Distance: 3.8365)
8. Kepler-1441 b (Distance: 3.8677)
9. Kepler-1965 b (Distance: 3.9333)
10. Kepler-1505 b (Distance: 3.9847)

### Preparing Dataset for Experiment #2 Ablation (No Spectral Type) KNN Models #15 and #16

In [ ]:
# removing all columns that start with spectral_type_ from the experiment_2_ablation dataframe
experiment_2_ablation_no_spec_type = experiment_2_ablation.drop(columns=[col for col in experiment_2_ablation.columns if col.startswith('spectral_type_')])
experiment_2_ablation_no_spec_type

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
planet_name,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,90.778824,1.305879,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,217.709668,1.349663,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,63.134826,1.528982,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,0.705033,0.566812,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,1.231895,0.782034,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,3.320113,4.655553,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,3.275493,1.254124,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,3.275493,0.717561,0.0
ups Leo b,1.0,1.054591,1.180000,11.410451,162.092488,2.371251,0.837838,11.220000,1.480000,2.460000,61.776135,1.120121,0.0
xi Aql b,1.0,0.374692,0.628333,21.628811,616.904938,3.262527,0.833420,11.430000,1.740000,2.635000,62.768708,1.664388,0.0

In [ ]:
# removing all columns that start with spectral_type_ from the earth dataframe
earth_no_spec_type = earth.drop(columns=[col for col in earth.columns if col.startswith('spectral_type_')])
earth_no_spec_type

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
planet_name,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

## **Experiment #2 Ablation (No Spectral Type) Manhattan Distance KNN Model #15**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_spec_type)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_spec_type)

# Retrieve the 10 closest planet names
closest_planets_man7 = experiment_2_ablation_no_spec_type.index[indices[0]].tolist()
closest_distances_man7 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man7[i]} (Distance: {closest_distances_man7[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.7993)
2. Kepler-1185 b (Distance: 7.7585)
3. Kepler-442 b (Distance: 8.1599)
4. Kepler-132 e (Distance: 8.4888)
5. Kepler-1126 c (Distance: 8.5760)
6. Kepler-438 b (Distance: 8.6220)
7. Kepler-1620 b (Distance: 8.6520)
8. Kepler-384 c (Distance: 8.7051)
9. Kepler-1638 b (Distance: 8.8194)
10. Kepler-1253 b (Distance: 8.8426)

## **Experiment #2 Ablation (No Spectral Type) Euclidean Distance KNN Model #16**

In [ ]:
#Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_spec_type)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_spec_type)

# Retrieve the 10 closest planet names
closest_planets_euc7 = experiment_2_ablation_no_spec_type.index[indices[0]].tolist()
closest_distances_euc7 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc7[i]} (Distance: {closest_distances_euc7[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.7907)
2. Kepler-1253 b (Distance: 3.8157)
3. Kepler-132 e (Distance: 3.8466)
4. Kepler-1620 b (Distance: 3.8597)
5. Kepler-384 c (Distance: 3.8933)
6. Kepler-130 d (Distance: 3.9603)
7. Kepler-1440 b (Distance: 3.9850)
8. Kepler-1498 b (Distance: 3.9960)
9. Kepler-442 b (Distance: 4.0038)
10. Kepler-1459 b (Distance: 4.0104)

### Preparing Dataset for Experiment #2 Ablation (No Habitable Zone) KNN Models #17 and #18

In [ ]:
# removing habitable zone column from the experiment_2_ablation dataframe
experiment_2_ablation_no_hab_zone = experiment_2_ablation.drop(columns=['habitable_zone_main_seq'])
experiment_2_ablation_no_hab_zone

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups Leo b,1.0,1.054591,1.180000,11.410451,162.092488,2.371251,0.837838,11.220000,1.480000,2.460000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xi Aql b,1.0,0.374692,0.628333,21.628811,616.904938,3.262527,0.833420,11.430000,1.740000,2.635000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# removing habitable zone column from the earth dataframe
earth_no_hab_zone = earth.drop(columns=['habitable_zone_main_seq'])
earth_no_hab_zone

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## **Experiment #2 Ablation (No Habitable Zone) Manhattan Distance KNN Model #17**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_hab_zone)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_hab_zone)

# Retrieve the 10 closest planet names
closest_planets_man8 = experiment_2_ablation_no_hab_zone.index[indices[0]].tolist()
closest_distances_man8 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man8[i]} (Distance: {closest_distances_man8[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 6.7585)
2. Kepler-452 b (Distance: 6.7993)
3. Kepler-132 e (Distance: 7.4888)
4. Kepler-1126 c (Distance: 7.5760)
5. Kepler-384 c (Distance: 7.7051)
6. Kepler-1253 b (Distance: 7.8426)
7. Kepler-1965 b (Distance: 7.9975)
8. Kepler-1440 b (Distance: 8.0092)
9. Kepler-1605 b (Distance: 8.0991)
10. Kepler-1505 b (Distance: 8.3436)

## **Experiment #2 Ablation (No Habitable Zone) Euclidean Distance KNN Model #18**

In [ ]:
#Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_hab_zone)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_hab_zone)

# Retrieve the 10 closest planet names
closest_planets_euc8 = experiment_2_ablation_no_hab_zone.index[indices[0]].tolist()
closest_distances_euc8 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc8[i]} (Distance: {closest_distances_euc8[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.6564)
2. Kepler-1253 b (Distance: 3.6823)
3. Kepler-132 e (Distance: 3.7144)
4. Kepler-384 c (Distance: 3.7627)
5. Kepler-130 d (Distance: 3.8319)
6. Kepler-1440 b (Distance: 3.8574)
7. Kepler-1498 b (Distance: 3.8688)
8. Kepler-1441 b (Distance: 3.9188)
9. Kepler-1965 b (Distance: 3.9808)
10. Kepler-1620 b (Distance: 3.9871)

### Preparing Dataset for Experiment #2 Ablation (No Temperature Features) KNN Models #19 and #20

In [ ]:
# removing temperature features from the experiment_2_ablation dataframe
experiment_2_ablation_no_temp = experiment_2_ablation.drop(columns=['planet_equil_temp_k', 'stellar_effective_temp_k'])
experiment_2_ablation_no_temp

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,13.760000,2.090000,2.380000,90.778824,1.305879,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,26.935000,2.780000,1.765000,217.709668,1.349663,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,11.275000,1.780000,2.590000,63.134826,1.528982,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.999085,0.904000,4.418006,0.705033,0.566812,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,1.129135,1.016599,4.342293,1.231895,0.782034,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,1.614742,1.276049,4.161529,3.320113,4.655553,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.614742,1.301399,4.148705,3.275493,1.254124,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,1.614742,1.301399,4.148705,3.275493,0.717561,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups Leo b,1.0,1.054591,1.180000,11.410451,162.092488,11.220000,1.480000,2.460000,61.776135,1.120121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xi Aql b,1.0,0.374692,0.628333,21.628811,616.904938,11.430000,1.740000,2.635000,62.768708,1.664388,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# removing temperature features from the earth dataframe
earth_no_temp = earth.drop(columns=['planet_equil_temp_k', 'stellar_effective_temp_k'])
earth_no_temp

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## **Experiment #2 Ablation (No Temperature Feature) Manhattan Distance KNN Model #19**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_temp)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_temp)

# Retrieve the 10 closest planet names
closest_planets_man9 = experiment_2_ablation_no_temp.index[indices[0]].tolist()
closest_distances_man9 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man9[i]} (Distance: {closest_distances_man9[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.7062)
2. Kepler-1185 b (Distance: 7.3187)
3. Kepler-1605 b (Distance: 7.3796)
4. Kepler-384 c (Distance: 7.7107)
5. Kepler-1440 b (Distance: 7.7497)
6. Kepler-1570 b (Distance: 7.7627)
7. Kepler-132 e (Distance: 7.8679)
8. Kepler-1253 b (Distance: 7.9355)
9. Kepler-1505 b (Distance: 7.9812)
10. Kepler-1965 b (Distance: 8.0580)

## **Experiment #2 Ablation (No Temperature Feature) Euclidean Distance KNN Model #20**

In [ ]:
#Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_temp)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_temp)

# Retrieve the 10 closest planet names
closest_planets_euc9 = experiment_2_ablation_no_temp.index[indices[0]].tolist()
closest_distances_euc9 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc9[i]} (Distance: {closest_distances_euc9[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1570 b (Distance: 3.6580)
2. Kepler-1253 b (Distance: 3.7085)
3. Kepler-1185 b (Distance: 3.7658)
4. Kepler-384 c (Distance: 3.7722)
5. Kepler-1440 b (Distance: 3.7817)
6. Kepler-132 e (Distance: 3.8004)
7. Kepler-1605 b (Distance: 3.8834)
8. Kepler-130 d (Distance: 3.8875)
9. Kepler-1441 b (Distance: 3.8964)
10. Kepler-1498 b (Distance: 3.8966)

-------------

# **Experiment #3: Weight Sensitivity Analysis**
The purpose of this experiment is to test whether the top Earth-like candidates remain stable when the feature weights are slightly changed.

Please use the current weighted Manhattan and weighted Euclidean models as the original/full models. Then create several modified weight settings and rerun the top 10 ranking.

-------------

Original weights using the current feature weights

In [ ]:
# already complete from our proposed method

Planetary features +20%: increase planet radius, planet mass, planet equilibrium temperature, and planetary orbital velocity weights by 20%

In [ ]:
# dataset for Planetary features +20% experiment #3
experiment_3_analysis_1 = experiment_3.copy()
experiment_3_analysis_1

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups Leo b,1.0,1.054591,1.180000,11.410451,162.092488,2.371251,0.837838,11.220000,1.480000,2.460000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xi Aql b,1.0,0.374692,0.628333,21.628811,616.904938,3.262527,0.833420,11.430000,1.740000,2.635000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# earth dataset for Planetary features +20% experiment #3
earth_3_analysis_1 = earth_3.copy()
earth_3_analysis_1

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# weights applied (planet features: +20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.2,
    'planet_mass_earth_mass': 1.2,
    'planet_equil_temp_k': 1.2,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.0,
    'stellar_mass_solar_mass': 1.0,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.2,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 1.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_1.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_1[col] *= weight
    earth_3_analysis_1[col] *= weight

## **Experiment #3 Weight Sensitivity Analysis (Planetary features +20%) Manhattan Distance KNN Model #21**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_1)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_1)

# Retrieve the 10 closest planet names
closest_planets_man10 = experiment_3_analysis_1.index[indices[0]].tolist()
closest_distances_man10 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man10[i]} (Distance: {closest_distances_man10[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 7.4018)
2. Kepler-1185 b (Distance: 8.1093)
3. Kepler-132 e (Distance: 8.7890)
4. Kepler-384 c (Distance: 9.1571)
5. Kepler-1126 c (Distance: 9.1665)
6. Kepler-1253 b (Distance: 9.3728)
7. Kepler-1965 b (Distance: 9.4585)
8. Kepler-1605 b (Distance: 9.5465)
9. Kepler-1440 b (Distance: 9.6013)
10. Kepler-1638 b (Distance: 9.7888)

## **Experiment #3 Weight Sensitivity Analysis (Planetary features +20%) Euclidean Distance KNN Model #22**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='euclidean', p=2).fit(experiment_3_analysis_1)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_1)

# Retrieve the 10 closest planet names
closest_planets_euc10 = experiment_3_analysis_1.index[indices[0]].tolist()
closest_distances_euc10 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc10[i]} (Distance: {closest_distances_euc10[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.8364)
2. Kepler-132 e (Distance: 3.8847)
3. Kepler-1253 b (Distance: 3.9216)
4. Kepler-384 c (Distance: 4.0028)
5. Kepler-130 d (Distance: 4.0439)
6. Kepler-1498 b (Distance: 4.0940)
7. Kepler-1440 b (Distance: 4.1454)
8. Kepler-1620 b (Distance: 4.1762)
9. Kepler-1441 b (Distance: 4.2063)
10. Kepler-1965 b (Distance: 4.2081)

Planetary features -20%: decrease those planetary feature weights by 20%

In [ ]:
# dataset for Planetary features -20% experiment #3
experiment_3_analysis_2 = experiment_3.copy()
experiment_3_analysis_2

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups Leo b,1.0,1.054591,1.180000,11.410451,162.092488,2.371251,0.837838,11.220000,1.480000,2.460000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xi Aql b,1.0,0.374692,0.628333,21.628811,616.904938,3.262527,0.833420,11.430000,1.740000,2.635000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# earth dataset for Planetary features -20% experiment #3
earth_3_analysis_2 = earth_3.copy()
earth_3_analysis_2

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# weights applied (planet features: -20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 0.8,
    'planet_mass_earth_mass': 0.8,
    'planet_equil_temp_k': 0.8,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.0,
    'stellar_mass_solar_mass': 1.0,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 0.8,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 1.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_2.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_2[col] *= weight
    earth_3_analysis_2[col] *= weight

## **Experiment #3 Weight Sensitivity Analysis (Planetary features -20%) Manhattan Distance KNN Model #23**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_2)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_2)

# Retrieve the 10 closest planet names
closest_planets_man11 = experiment_3_analysis_2.index[indices[0]].tolist()
closest_distances_man11 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man11[i]} (Distance: {closest_distances_man11[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.1968)
2. Kepler-1185 b (Distance: 7.4077)
3. Kepler-1638 b (Distance: 7.8500)
4. Kepler-1126 c (Distance: 7.9855)
5. Kepler-132 e (Distance: 8.1886)
6. Kepler-384 c (Distance: 8.2530)
7. Kepler-1253 b (Distance: 8.3123)
8. Kepler-51 e (Distance: 8.3883)
9. Kepler-1440 b (Distance: 8.4172)
10. Kepler-1965 b (Distance: 8.5365)

## **Experiment #3 Weight Sensitivity Analysis (Planetary features -20%) Euclidean Distance KNN Model #24**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_2)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_2)

# Retrieve the 10 closest planet names
closest_planets_euc11 = experiment_3_analysis_2.index[indices[0]].tolist()
closest_distances_euc11 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc11[i]} (Distance: {closest_distances_euc11[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1253 b (Distance: 3.7268)
2. Kepler-1185 b (Distance: 3.7530)
3. Kepler-384 c (Distance: 3.8015)
4. Kepler-132 e (Distance: 3.8152)
5. Kepler-1440 b (Distance: 3.8487)
6. Kepler-130 d (Distance: 3.8905)
7. Kepler-1441 b (Distance: 3.9070)
8. Kepler-1498 b (Distance: 3.9139)
9. Kepler-452 b (Distance: 3.9408)
10. Kepler-1570 b (Distance: 3.9981)

Full Stellar features +20%: increase stellar mass, stellar radius, stellar effective temperature, stellar luminosity, stellar surface gravity weights, and spectral type by 20%

In [ ]:
# datasets for full stellar features +20% experiment #3
experiment_3_analysis_3 = experiment_3.copy()
earth_3_analysis_3 = earth_3.copy()

In [ ]:
# weights applied (full stellar features: +20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 1.2,
    'stellar_rad_solar_rad': 1.2,
    'stellar_mass_solar_mass': 1.2,
    'stellar_surf_grav': 1.2,
    'stellar_luminosity_solar_lum': 1.2,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.2,
    'spectral_type_AIV': 1.2,
    'spectral_type_AV': 1.2,
    'spectral_type_BIV': 1.2,
    'spectral_type_BV': 1.2,
    'spectral_type_FIV': 1.2,
    'spectral_type_FV': 1.2,
    'spectral_type_GII': 1.2,
    'spectral_type_GIII': 1.2,
    'spectral_type_GIV': 1.2,
    'spectral_type_GV': 1.2,
    'spectral_type_KII': 1.2,
    'spectral_type_KIII': 1.2,
    'spectral_type_KIV': 1.2,
    'spectral_type_KV': 1.2,
    'spectral_type_MIII': 1.2,
    'spectral_type_MV': 1.2,
    'spectral_type_SD': 1.2,
    'spectral_type_T': 1.2,
    'spectral_type_WD': 1.2,
    'spectral_type_sdB': 1.2,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_3.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_3[col] *= weight
    earth_3_analysis_3[col] *= weight

### **Experiment #3 Weight Sensitivity Analysis (Full Stellar features +20%) Manhattan Distance KNN Model #25**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_3)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_3)

# Retrieve the 10 closest planet names
closest_planets_man12 = experiment_3_analysis_3.index[indices[0]].tolist()
closest_distances_man12 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man12[i]} (Distance: {closest_distances_man12[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 7.5440)
2. Kepler-1185 b (Distance: 8.5042)
3. Kepler-132 e (Distance: 9.2344)
4. Kepler-1126 c (Distance: 9.3381)
5. Kepler-384 c (Distance: 9.4660)
6. Kepler-1638 b (Distance: 9.5127)
7. Kepler-1253 b (Distance: 9.5815)
8. Kepler-1440 b (Distance: 9.6862)
9. Kepler-1965 b (Distance: 9.8050)
10. Kepler-1605 b (Distance: 10.0028)

### **Experiment #3 Weight Sensitivity Analysis (Full Stellar features +20%) Euclidean Distance KNN Model #26**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_3)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_3)

# Retrieve the 10 closest planet names
closest_planets_euc12 = experiment_3_analysis_3.index[indices[0]].tolist()
closest_distances_euc12 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc12[i]} (Distance: {closest_distances_euc12[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1253 b (Distance: 4.3829)
2. Kepler-1185 b (Distance: 4.4205)
3. Kepler-132 e (Distance: 4.4474)
4. Kepler-384 c (Distance: 4.4642)
5. Kepler-1440 b (Distance: 4.5288)
6. Kepler-130 d (Distance: 4.5399)
7. Kepler-1441 b (Distance: 4.6004)
8. Kepler-1498 b (Distance: 4.6019)
9. Kepler-1965 b (Distance: 4.7279)
10. Kepler-1505 b (Distance: 4.7324)

Full Stellar features -20%: decrease those full stellar feature weights by 20%

In [ ]:
# datasets for full stellar features +20% experiment #3
experiment_3_analysis_4 = experiment_3.copy()
earth_3_analysis_4 = earth_3.copy()

In [ ]:
# weights applied (full stellar features: -20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 0.8,
    'stellar_rad_solar_rad': 0.8,
    'stellar_mass_solar_mass': 0.8,
    'stellar_surf_grav': 0.8,
    'stellar_luminosity_solar_lum': 0.8,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 0.8,
    'spectral_type_AIV': 0.8,
    'spectral_type_AV': 0.8,
    'spectral_type_BIV': 0.8,
    'spectral_type_BV': 0.8,
    'spectral_type_FIV': 0.8,
    'spectral_type_FV': 0.8,
    'spectral_type_GII': 0.8,
    'spectral_type_GIII': 0.8,
    'spectral_type_GIV': 0.8,
    'spectral_type_GV': 0.8,
    'spectral_type_KII': 0.8,
    'spectral_type_KIII': 0.8,
    'spectral_type_KIV': 0.8,
    'spectral_type_KV': 0.8,
    'spectral_type_MIII': 0.8,
    'spectral_type_MV': 0.8,
    'spectral_type_SD': 0.8,
    'spectral_type_T': 0.8,
    'spectral_type_WD': 0.8,
    'spectral_type_sdB': 0.8,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_4.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_4[col] *= weight
    earth_3_analysis_4[col] *= weight

### **Experiment #3 Weight Sensitivity Analysis (Full Stellar features -20%) Manhattan Distance KNN Model #27**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_4)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_4)

# Retrieve the 10 closest planet names
closest_planets_man13 = experiment_3_analysis_4.index[indices[0]].tolist()
closest_distances_man13 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man13[i]} (Distance: {closest_distances_man13[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.0546)
2. Kepler-1185 b (Distance: 7.0128)
3. Kepler-132 e (Distance: 7.7432)
4. Kepler-1126 c (Distance: 7.8139)
5. Kepler-384 c (Distance: 7.9442)
6. Kepler-1253 b (Distance: 8.1037)
7. Kepler-1638 b (Distance: 8.1260)
8. Kepler-1965 b (Distance: 8.1900)
9. Kepler-1605 b (Distance: 8.1953)
10. Kepler-1440 b (Distance: 8.3322)

### **Experiment #3 Weight Sensitivity Analysis (Full Stellar features -20%) Euclidean Distance KNN Model #28**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_4)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_4)

# Retrieve the 10 closest planet names
closest_planets_euc13 = experiment_3_analysis_4.index[indices[0]].tolist()
closest_distances_euc13 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc13[i]} (Distance: {closest_distances_euc13[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.1841)
2. Kepler-132 e (Distance: 3.2741)
3. Kepler-1253 b (Distance: 3.2795)
4. Kepler-384 c (Distance: 3.3548)
5. Kepler-130 d (Distance: 3.4136)
6. Kepler-1498 b (Distance: 3.4212)
7. Kepler-1620 b (Distance: 3.4529)
8. Kepler-1440 b (Distance: 3.4772)
9. Kepler-442 b (Distance: 3.4794)
10. Kepler-1965 b (Distance: 3.5131)

Partial Stellar features +20%: increase stellar mass, stellar radius, stellar effective temperature, stellar luminosity, and stellar surface gravity weights by 20%

In [ ]:
# datasets for partial stellar features +20% experiment #3
experiment_3_analysis_5 = experiment_3.copy()
earth_3_analysis_5 = earth_3.copy()

In [ ]:
# weights applied (partial stellar features: +20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 1.2,
    'stellar_rad_solar_rad': 1.2,
    'stellar_mass_solar_mass': 1.2,
    'stellar_surf_grav': 1.2,
    'stellar_luminosity_solar_lum': 1.2,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 1.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_5.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_5[col] *= weight
    earth_3_analysis_5[col] *= weight

model #29

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_5)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_5)

# Retrieve the 10 closest planet names
closest_planets_man14 = experiment_3_analysis_5.index[indices[0]].tolist()
closest_distances_man14 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man14[i]} (Distance: {closest_distances_man14[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 7.5440)
2. Kepler-1185 b (Distance: 8.5042)
3. Kepler-132 e (Distance: 9.2344)
4. Kepler-1126 c (Distance: 9.3381)
5. Kepler-384 c (Distance: 9.4660)
6. Kepler-1638 b (Distance: 9.5127)
7. Kepler-1253 b (Distance: 9.5815)
8. Kepler-1440 b (Distance: 9.6862)
9. Kepler-1965 b (Distance: 9.8050)
10. Kepler-1605 b (Distance: 10.0028)

model #30

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_5)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_5)

# Retrieve the 10 closest planet names
closest_planets_euc14 = experiment_3_analysis_5.index[indices[0]].tolist()
closest_distances_euc14 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc14[i]} (Distance: {closest_distances_euc14[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1253 b (Distance: 4.3829)
2. Kepler-1185 b (Distance: 4.4205)
3. Kepler-132 e (Distance: 4.4474)
4. Kepler-384 c (Distance: 4.4642)
5. Kepler-1440 b (Distance: 4.5288)
6. Kepler-130 d (Distance: 4.5399)
7. Kepler-1441 b (Distance: 4.6004)
8. Kepler-1498 b (Distance: 4.6019)
9. Kepler-1620 b (Distance: 4.7008)
10. Kepler-1965 b (Distance: 4.7279)

Partial Stellar features -20%: decrease those partial stellar feature weights by 20%

In [ ]:
# datasets for partial stellar features -20% experiment #3
experiment_3_analysis_6 = experiment_3.copy()
earth_3_analysis_6 = earth_3.copy()

In [ ]:
# weights applied (partial stellar features: -20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 0.8,
    'stellar_rad_solar_rad': 0.8,
    'stellar_mass_solar_mass': 0.8,
    'stellar_surf_grav': 0.8,
    'stellar_luminosity_solar_lum': 0.8,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 1.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_6.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_6[col] *= weight
    earth_3_analysis_6[col] *= weight

model #31

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_6)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_6)

# Retrieve the 10 closest planet names
closest_planets_man15 = experiment_3_analysis_6.index[indices[0]].tolist()
closest_distances_man15 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man15[i]} (Distance: {closest_distances_man15[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.0546)
2. Kepler-1185 b (Distance: 7.0128)
3. Kepler-132 e (Distance: 7.7432)
4. Kepler-1126 c (Distance: 7.8139)
5. Kepler-384 c (Distance: 7.9442)
6. Kepler-1253 b (Distance: 8.1037)
7. Kepler-1638 b (Distance: 8.1260)
8. Kepler-1965 b (Distance: 8.1900)
9. Kepler-1605 b (Distance: 8.1953)
10. Kepler-1440 b (Distance: 8.3322)

model #32

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_6)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_6)

# Retrieve the 10 closest planet names
closest_planets_euc15 = experiment_3_analysis_6.index[indices[0]].tolist()
closest_distances_euc15 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc15[i]} (Distance: {closest_distances_euc15[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.1841)
2. Kepler-132 e (Distance: 3.2741)
3. Kepler-1253 b (Distance: 3.2795)
4. Kepler-384 c (Distance: 3.3548)
5. Kepler-130 d (Distance: 3.4136)
6. Kepler-1498 b (Distance: 3.4212)
7. Kepler-1440 b (Distance: 3.4772)
8. Kepler-1965 b (Distance: 3.5131)
9. Kepler-1441 b (Distance: 3.5249)
10. Kepler-1620 b (Distance: 3.5556)

Spectral-type features +20%: increase the one-hot encoded spectral-type feature weights by 20%

In [ ]:
# datasets for partial stellar features +20% experiment #3
experiment_3_analysis_7 = experiment_3.copy()
earth_3_analysis_7 = earth_3.copy()

In [ ]:
# weights applied (one hot encoded spectral features: +20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.0,
    'stellar_mass_solar_mass': 1.0,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.2,
    'spectral_type_AIV': 1.2,
    'spectral_type_AV': 1.2,
    'spectral_type_BIV': 1.2,
    'spectral_type_BV': 1.2,
    'spectral_type_FIV': 1.2,
    'spectral_type_FV': 1.2,
    'spectral_type_GII': 1.2,
    'spectral_type_GIII': 1.2,
    'spectral_type_GIV': 1.2,
    'spectral_type_GV': 1.2,
    'spectral_type_KII': 1.2,
    'spectral_type_KIII': 1.2,
    'spectral_type_KIV': 1.2,
    'spectral_type_KV': 1.2,
    'spectral_type_MIII': 1.2,
    'spectral_type_MV': 1.2,
    'spectral_type_SD': 1.2,
    'spectral_type_T': 1.2,
    'spectral_type_WD': 1.2,
    'spectral_type_sdB': 1.2,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_7.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_7[col] *= weight
    earth_3_analysis_7[col] *= weight

model #33

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_7)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_7)

# Retrieve the 10 closest planet names
closest_planets_man16 = experiment_3_analysis_7.index[indices[0]].tolist()
closest_distances_man16 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man16[i]} (Distance: {closest_distances_man16[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.7993)
2. Kepler-1185 b (Distance: 7.7585)
3. Kepler-132 e (Distance: 8.4888)
4. Kepler-1126 c (Distance: 8.5760)
5. Kepler-384 c (Distance: 8.7051)
6. Kepler-1638 b (Distance: 8.8194)
7. Kepler-1253 b (Distance: 8.8426)
8. Kepler-1965 b (Distance: 8.9975)
9. Kepler-1440 b (Distance: 9.0092)
10. Kepler-1605 b (Distance: 9.0991)

model #34

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_7)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_7)

# Retrieve the 10 closest planet names
closest_planets_euc16 = experiment_3_analysis_7.index[indices[0]].tolist()
closest_distances_euc16 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc16[i]} (Distance: {closest_distances_euc16[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.7907)
2. Kepler-1253 b (Distance: 3.8157)
3. Kepler-132 e (Distance: 3.8466)
4. Kepler-384 c (Distance: 3.8933)
5. Kepler-130 d (Distance: 3.9603)
6. Kepler-1440 b (Distance: 3.9850)
7. Kepler-1498 b (Distance: 3.9960)
8. Kepler-1441 b (Distance: 4.0444)
9. Kepler-1965 b (Distance: 4.1045)
10. Kepler-1505 b (Distance: 4.1683)

Spectral-type features -20%: decrease the one-hot encoded spectral-type feature weights by 20%

In [ ]:
# datasets for partial stellar features +20% experiment #3
experiment_3_analysis_8 = experiment_3.copy()
earth_3_analysis_8 = earth_3.copy()

In [ ]:
# weights applied (one hot encoded spectral features: -20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.0,
    'stellar_mass_solar_mass': 1.0,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 0.8,
    'spectral_type_AIV': 0.8,
    'spectral_type_AV': 0.8,
    'spectral_type_BIV': 0.8,
    'spectral_type_BV': 0.8,
    'spectral_type_FIV': 0.8,
    'spectral_type_FV': 0.8,
    'spectral_type_GII': 0.8,
    'spectral_type_GIII': 0.8,
    'spectral_type_GIV': 0.8,
    'spectral_type_GV': 0.8,
    'spectral_type_KII': 0.8,
    'spectral_type_KIII': 0.8,
    'spectral_type_KIV': 0.8,
    'spectral_type_KV': 0.8,
    'spectral_type_MIII': 0.8,
    'spectral_type_MV': 0.8,
    'spectral_type_SD': 0.8,
    'spectral_type_T': 0.8,
    'spectral_type_WD': 0.8,
    'spectral_type_sdB': 0.8,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_8.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_8[col] *= weight
    earth_3_analysis_8[col] *= weight

model #35

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_8)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_8)

# Retrieve the 10 closest planet names
closest_planets_man17 = experiment_3_analysis_8.index[indices[0]].tolist()
closest_distances_man17 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man17[i]} (Distance: {closest_distances_man17[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.7993)
2. Kepler-1185 b (Distance: 7.7585)
3. Kepler-132 e (Distance: 8.4888)
4. Kepler-1126 c (Distance: 8.5760)
5. Kepler-384 c (Distance: 8.7051)
6. Kepler-1638 b (Distance: 8.8194)
7. Kepler-1253 b (Distance: 8.8426)
8. Kepler-1965 b (Distance: 8.9975)
9. Kepler-1440 b (Distance: 9.0092)
10. Kepler-1605 b (Distance: 9.0991)

model #36

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_8)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_8)

# Retrieve the 10 closest planet names
closest_planets_euc17 = experiment_3_analysis_8.index[indices[0]].tolist()
closest_distances_euc17 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc17[i]} (Distance: {closest_distances_euc17[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.7907)
2. Kepler-1253 b (Distance: 3.8157)
3. Kepler-132 e (Distance: 3.8466)
4. Kepler-384 c (Distance: 3.8933)
5. Kepler-130 d (Distance: 3.9603)
6. Kepler-1440 b (Distance: 3.9850)
7. Kepler-1498 b (Distance: 3.9960)
8. Kepler-1620 b (Distance: 4.0221)
9. Kepler-1441 b (Distance: 4.0444)
10. Kepler-1965 b (Distance: 4.1045)

Orbital/HZ features +20%: increase orbital period, orbital semi-major axis, and habitable-zone flag weights by 20%

In [ ]:
# datasets for partial stellar features +20% experiment #3
experiment_3_analysis_9 = experiment_3.copy()
earth_3_analysis_9 = earth_3.copy()

In [ ]:
# weights applied (orbital and habitable features: +20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.2,
    'orbit_semi_major_axis_au': 1.2,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.0,
    'stellar_mass_solar_mass': 1.0,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 1.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 1.2,
}

# Apply weights (note: all weights = 1.0)
for col in experiment_3_analysis_9.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_9[col] *= weight
    earth_3_analysis_9[col] *= weight

model #37

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_9)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_9)

# Retrieve the 10 closest planet names
closest_planets_man18 = experiment_3_analysis_9.index[indices[0]].tolist()
closest_distances_man18 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man18[i]} (Distance: {closest_distances_man18[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.8120)
2. Kepler-1185 b (Distance: 8.2137)
3. Kepler-1638 b (Distance: 8.9206)
4. Kepler-1126 c (Distance: 8.9386)
5. Kepler-132 e (Distance: 8.9407)
6. Kepler-384 c (Distance: 9.2331)
7. Kepler-1253 b (Distance: 9.3419)
8. Kepler-51 e (Distance: 9.4544)
9. Kepler-1965 b (Distance: 9.5285)
10. Kepler-1440 b (Distance: 9.5420)

model #38

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_9)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_9)

# Retrieve the 10 closest planet names
closest_planets_euc18 = experiment_3_analysis_9.index[indices[0]].tolist()
closest_distances_euc18 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc18[i]} (Distance: {closest_distances_euc18[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.8952)
2. Kepler-1253 b (Distance: 3.9365)
3. Kepler-132 e (Distance: 3.9484)
4. Kepler-384 c (Distance: 4.0240)
5. Kepler-130 d (Distance: 4.0680)
6. Kepler-1440 b (Distance: 4.1149)
7. Kepler-1498 b (Distance: 4.1219)
8. Kepler-1441 b (Distance: 4.1728)
9. Kepler-452 b (Distance: 4.1918)
10. Kepler-1620 b (Distance: 4.2081)

Orbital/HZ features -20%: decrease those orbital/HZ feature weights by 20%

In [ ]:
# datasets for partial stellar features +20% experiment #3
experiment_3_analysis_10 = experiment_3.copy()
earth_3_analysis_10 = earth_3.copy()

In [ ]:
# weights applied (orbital and habitable features: -20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 0.8,
    'orbit_semi_major_axis_au': 0.8,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.0,
    'stellar_mass_solar_mass': 1.0,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 1.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 0.8,
}

# Apply weights (note: all weights = 1.0)
for col in experiment_3_analysis_10.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_10[col] *= weight
    earth_3_analysis_10[col] *= weight

model #39

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_10)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_10)

# Retrieve the 10 closest planet names
closest_planets_man19 = experiment_3_analysis_10.index[indices[0]].tolist()
closest_distances_man19 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man19[i]} (Distance: {closest_distances_man19[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.7866)
2. Kepler-1185 b (Distance: 7.3033)
3. Kepler-132 e (Distance: 8.0369)
4. Kepler-384 c (Distance: 8.1770)
5. Kepler-1126 c (Distance: 8.2133)
6. Kepler-1253 b (Distance: 8.3432)
7. Kepler-1965 b (Distance: 8.4665)
8. Kepler-1440 b (Distance: 8.4764)
9. Kepler-1605 b (Distance: 8.6304)
10. Kepler-1638 b (Distance: 8.7182)

model #40

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_10)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_10)

# Retrieve the 10 closest planet names
closest_planets_euc19 = experiment_3_analysis_10.index[indices[0]].tolist()
closest_distances_euc19 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc19[i]} (Distance: {closest_distances_euc19[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.7030)
2. Kepler-1253 b (Distance: 3.7139)
3. Kepler-132 e (Distance: 3.7613)
4. Kepler-384 c (Distance: 3.7831)
5. Kepler-130 d (Distance: 3.8699)
6. Kepler-1440 b (Distance: 3.8754)
7. Kepler-1498 b (Distance: 3.8899)
8. Kepler-1441 b (Distance: 3.9362)
9. Kepler-1965 b (Distance: 3.9989)
10. Kepler-1620 b (Distance: 4.0292)

-------------

# **Experiment 4: Imputation Sensitivity Analysis**
The purpose of this experiment is to check whether the ranking depends too heavily on imputed values.

Since several important exoplanet features had missing values before imputation, we need to compare the current final imputed dataset with a more conservative version of the data.

-------------

### **Full imputed dataset: the current final dataset after all imputation steps**

In [ ]:
# already complete from our propsoed method

### **Reduced-feature dataset: remove highly imputed features, such as planet mass and/or spectral type, and rerun the ranking using the remaining features**

In [ ]:
# loading dataset
experiment_4 = pd.read_csv('/content/drive/MyDrive/Exoplanet /filtered_2026_dataset_new_final.csv')

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

spectral_type               68.57%
planet_mass_earth_mass      47.62%
planet_mass_jupiter_mass    47.62%
planet_equil_temp_k         26.90%
planet_rad_jupiter_rad      24.91%
planet_rad_earth_rad        24.91%
orbital_eccentricity        14.87%
stellar_metallicity         11.68%
stellar_surf_grav           10.69%
stellar_rad_solar_rad        9.98%
stellar_effective_temp_k     7.68%
orbital_period_day           5.24%
orbit_semi_major_axis_au     5.09%
distance_parsec              2.03%
stellar_mass_solar_mass      0.66%
year_of_discovery            0.00%
host_star_name               0.00%
planet_name                  0.00%
discovery_method             0.00%
star_number_per_system       0.00%
discovery_facility           0.00%
dtype: object

#### Extracting key features

In [ ]:
# removing non-key feature columns
experiment_4 = experiment_4.drop(columns=['planet_mass_jupiter_mass', 'planet_rad_jupiter_rad', 'orbital_eccentricity', 'stellar_metallicity', 'distance_parsec',
                                                   'year_of_discovery', 'host_star_name', 'discovery_method', 'discovery_facility'])

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

spectral_type               68.57%
planet_mass_earth_mass      47.62%
planet_equil_temp_k         26.90%
planet_rad_earth_rad        24.91%
stellar_surf_grav           10.69%
stellar_rad_solar_rad        9.98%
stellar_effective_temp_k     7.68%
orbital_period_day           5.24%
orbit_semi_major_axis_au     5.09%
stellar_mass_solar_mass      0.66%
planet_name                  0.00%
star_number_per_system       0.00%
dtype: object

In [ ]:
# creating copy of datset for experiemnt #5
experiment_5 = experiment_4.copy()

In [ ]:
# removing columns with a missing percentage above 30%
experiment_4 = experiment_4.drop(columns=['spectral_type', 'planet_mass_earth_mass'])

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_equil_temp_k         26.90%
planet_rad_earth_rad        24.91%
stellar_surf_grav           10.69%
stellar_rad_solar_rad        9.98%
stellar_effective_temp_k     7.68%
orbital_period_day           5.24%
orbit_semi_major_axis_au     5.09%
stellar_mass_solar_mass      0.66%
star_number_per_system       0.00%
planet_name                  0.00%
dtype: object

#### Imputing missing values

In [ ]:
# Imputing the missing value for stellar mass using the Law of Universal Gravitaion

# For: Ms = (a^3)/(T^2) where a is the orbital semi major axis, T is the orbital period, and Ms is the stellar mass in terms of the Sun's mass (normalized)

# Constants and convertion factors
# the orbital_period will be converted from earth days to earth years
days_to_years = 1 / 365.25

# Create a boolean mask (series of TRUE and FALSE per row) to avoid division by zero or missing inputs
# Each row must be TRUE for all (no missing orbital semi major axis data, no missing orbital period data, all orbital period data greater than zero)
valid_inputs = (
    # For all orbital semi major axis (distance between star and planet) entries not missing and
    experiment_4["orbit_semi_major_axis_au"].notna() &
    # For all orbital period (time it takes the planet to orbit its star) entries not missing and
    experiment_4["orbital_period_day"].notna() &
    # For all orbital period entries greater than (but never equal to) zero
    (experiment_4["orbital_period_day"] > 0)
)

# Mask of rows to be modified for the stellar mass column where the stellar mass entry is missing TRUE and satisfies the valid inputs TRUE
mask = experiment_4["stellar_mass_solar_mass"].isna() & valid_inputs

# For the specific rows in stellar mass with missing mass entry, apply the mask
experiment_4.loc[mask, "stellar_mass_solar_mass"] = (
    experiment_4.loc[mask, "orbit_semi_major_axis_au"]**3
    / (experiment_4.loc[mask, "orbital_period_day"]*days_to_years)**2
)

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_equil_temp_k         26.90%
planet_rad_earth_rad        24.91%
stellar_surf_grav           10.69%
stellar_rad_solar_rad        9.98%
stellar_effective_temp_k     7.68%
orbital_period_day           5.24%
orbit_semi_major_axis_au     5.09%
stellar_mass_solar_mass      0.53%
star_number_per_system       0.00%
planet_name                  0.00%
dtype: object

In [ ]:
# Imputing the missing value for stellar mass using the Law of Universal Gravitaion

# For: Ms = (g Rs^(2))/G where g is the stellar surface gravity, Rs is the stellar radius and and G is the gravitational constant

# Constants and conversion factors
G = 6.67430e-11    # m^3 kg^-1 s^-2
M_sun = 1.989e30   # kg
R_sun = 6.96e8     # m

# Valid inputs: stellar radius and surface gravity (log g) known
valid_inputs = (
    experiment_4["stellar_rad_solar_rad"].notna() &
    experiment_4["stellar_surf_grav"].notna()
)

# Mask of rows to be modified for the stellar mass column where the stellar mass entry is missing TRUE and satisfies the valid inputs TRUE
mask2 = experiment_4["stellar_mass_solar_mass"].isna() & valid_inputs

# Convert log(g) [cgs] to g [m/s^2]
g_m_s2 = 10 ** experiment_4.loc[mask2, "stellar_surf_grav"] / 100

# Convert stellar radius from sun radius to meters
R_m = experiment_4.loc[mask2, "stellar_rad_solar_rad"] * R_sun

# Compute stellar mass in sun masses
experiment_4.loc[mask2, "stellar_mass_solar_mass"] = ((g_m_s2 * R_m**2) / G) / M_sun

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_equil_temp_k         26.90%
planet_rad_earth_rad        24.91%
stellar_surf_grav           10.69%
stellar_rad_solar_rad        9.98%
stellar_effective_temp_k     7.68%
orbital_period_day           5.24%
orbit_semi_major_axis_au     5.09%
stellar_mass_solar_mass      0.41%
star_number_per_system       0.00%
planet_name                  0.00%
dtype: object

In [ ]:
# Imputing the missing value for orbital semi major axis using Kepler's Third Law Equations

# For: a = (T^2 * Ms)^(1/3) where a is the orbital semi major axis, T is the orbital period, and Ms is the stellar mass in terms of the Sun's mass (normalized)

# Constants and conversion factors
# the orbital_period will be converted from earth days to earth years
days_to_years = 1 / 365.25

# Create a boolean mask (series of TRUE and FALSE per row) to avoid division by zero or missing inputs
# Each row must be TRUE for all (no missing orbital semi major axis data, no missing orbital period data, all orbital period data greater than zero)
valid_inputs = (
    # For all orbital period (time it takes the planet to orbit its star) entries not missing and
    experiment_4["orbital_period_day"].notna() &
    # For all stellar mass entries not missing
    experiment_4["stellar_mass_solar_mass"].notna()
)

# Mask of rows to be modified for the stellar mass column where the orbital semi major axis entry is missing TRUE and satisfys the valid inputs TRUE
mask = experiment_4["orbit_semi_major_axis_au"].isna() & valid_inputs

# For the specific rows in orbital semi major axis with missing mass entry, apply the mask
experiment_4.loc[mask, "orbit_semi_major_axis_au"] = (
    experiment_4.loc[mask, "stellar_mass_solar_mass"] * (experiment_4.loc[mask, "orbital_period_day"] * days_to_years)**2)**(1/3)

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_equil_temp_k         26.90%
planet_rad_earth_rad        24.91%
stellar_surf_grav           10.69%
stellar_rad_solar_rad        9.98%
stellar_effective_temp_k     7.68%
orbital_period_day           5.24%
stellar_mass_solar_mass      0.41%
orbit_semi_major_axis_au     0.18%
star_number_per_system       0.00%
planet_name                  0.00%
dtype: object

In [ ]:
# Imputing the missing value for orbital period using Kepler's Third Law Equations

# For: T = (a^3 * Ms)^(1/2) where a is the orbital semi major axis, T is the orbital period, and Ms is the stellar mass in terms of the Sun's mass (normalized)

# Constants and conversion factors
# the orbital_period will be converted from earth years to earth days
years_to_days = 365.25

# Create a boolean mask (series of TRUE and FALSE per row) to avoid division by zero or missing inputs
# Each row must be TRUE for all (no missing orbital semi major axis data, no missing orbital period data, all orbital period data greater than zero)
valid_inputs = (
    # For all orbital period (time it takes the planet to orbit its star) entries not missing and
    experiment_4["orbit_semi_major_axis_au"].notna() &
    # For all stellar mass entries not missing and
    experiment_4["stellar_mass_solar_mass"].notna() &
    # For all stelar mass entries greater than (but never equal to) zero
    (experiment_4["stellar_mass_solar_mass"] > 0)
)

# Mask of rows to be modified for the stellar mass column where the orbital semi major axis entry is missing TRUE and satisfys the valid inputs TRUE
mask = experiment_4["orbital_period_day"].isna() & valid_inputs

# Create a boolean mask (series of TRUE and FALSE per row) to avoid division by zero or missing inputs
# Each row must be TRUE for all (no missing orbital semi major axis data, no missing orbital period data, all orbital period data greater than zero)
valid_inputs = (
    # For all orbital semi major axis (distance between planet and its star) entries not missing and
    experiment_4["orbit_semi_major_axis_au"].notna() &
    # For all stellar mass entries not missing and
    experiment_4["stellar_mass_solar_mass"].notna() &
    # For all stelar mass entries greater than (but never equal to) zero
    (experiment_4["stellar_mass_solar_mass"] > 0)
)

# Mask of rows to be modified for the orbital period column where the orbital period entry is missing TRUE and satisfies the valid inputs TRUE
mask = experiment_4["orbital_period_day"].isna() & valid_inputs

# For the specific rows in orbital period with missing mass entry, apply the mask
experiment_4.loc[mask, "orbital_period_day"] = (
    (experiment_4.loc[mask, "orbit_semi_major_axis_au"])**3 / experiment_4.loc[mask, "stellar_mass_solar_mass"])**(1/3)

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_equil_temp_k         26.90%
planet_rad_earth_rad        24.91%
stellar_surf_grav           10.69%
stellar_rad_solar_rad        9.98%
stellar_effective_temp_k     7.68%
orbital_period_day           0.44%
stellar_mass_solar_mass      0.41%
orbit_semi_major_axis_au     0.18%
star_number_per_system       0.00%
planet_name                  0.00%
dtype: object

In [ ]:
# Imputing the missing value for stellar surface gravity using the Law of Universal Gravitation

# For: g = (GMs)/(Rs^(2)) where g is the stellar surface gravity, Rs is the stellar radius and and G is the gravitational constant

# Constants and conversion factors
G = 6.67430e-11    # m^3 kg^-1 s^-2
M_sun = 1.989e30   # kg
R_sun = 6.96e8     # m

# Valid inputs: stellar mass and stellar radius known
valid_inputs = (
    experiment_4["stellar_mass_solar_mass"].notna() &
    experiment_4["stellar_rad_solar_rad"].notna() &
    (experiment_4["stellar_mass_solar_mass"] > 0) &
    (experiment_4["stellar_rad_solar_rad"] > 0)
)

# Mask of rows to be modified for the stellar surface gravity log(g) [cgs] column where the stellar surface entry is missing TRUE and satisfies the valid inputs TRUE
mask = experiment_4["stellar_surf_grav"].isna() & valid_inputs

# Convert stellar mass from solar masses to kg
M_kg = experiment_4.loc[mask, "stellar_mass_solar_mass"] * M_sun

# Convert stellar radius from solar radii to meters
R_m = experiment_4.loc[mask, "stellar_rad_solar_rad"] * R_sun

# Compute surface gravity in m/s^2
g_m_s2 = G * M_kg / (R_m ** 2)

# Convert m/s^2 → cm/s^2
g_cgs = g_m_s2 * 100

# Store log10(g) (cgs)
experiment_4.loc[mask, "stellar_surf_grav"] = np.log10(g_cgs)

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_equil_temp_k         26.90%
planet_rad_earth_rad        24.91%
stellar_rad_solar_rad        9.98%
stellar_surf_grav            8.17%
stellar_effective_temp_k     7.68%
orbital_period_day           0.44%
stellar_mass_solar_mass      0.41%
orbit_semi_major_axis_au     0.18%
star_number_per_system       0.00%
planet_name                  0.00%
dtype: object

In [ ]:
# Imputing the missing value for stellar effective temp using Zero-Greenhouse Equilibrium Temperature of Exoplanet Equation

# For: T_eff = (T_eq/(1 - A)^(1/4)) * sqrt((2a)/Rs) where Rs is the stellar radius in sun radius and a is the orbital semi major axis (coverted from AU to Solar Radius)
# and T_eff is the stellar effective temperature

# Constants
AU_to_Rsun = 215.032    # 1 AU = 215.032 solar radii
A = 0.5                 # Bond albedo (assumed A = 0.5 neither hihgly reflective nor completely dark)

# Valid inputs: stellar temperature [K], stellar radius [R_sun], semi-major axis [AU]
valid_inputs = (
    experiment_4["planet_equil_temp_k"].notna() &
    experiment_4["orbit_semi_major_axis_au"].notna() &
    experiment_4["stellar_rad_solar_rad"].notna() &
    (experiment_4["stellar_rad_solar_rad"] > 0) &
    (experiment_4["orbit_semi_major_axis_au"] > 0)
)

# Mask rows where stellar effective temperature is missing
mask = experiment_4["stellar_effective_temp_k"].isna() & valid_inputs

# Planetary equilibrium effective temperature already in Kelvin
T_eq = experiment_4.loc[mask, "planet_equil_temp_k"]

# Convert semi-major axis from AU to sun radius since a/Rs must be dimensionless
a_Rsun = (
    experiment_4.loc[mask, "orbit_semi_major_axis_au"] * AU_to_Rsun
)

# Stellar radius already in sun radius
Rs = experiment_4.loc[mask, "stellar_rad_solar_rad"]

# Compute planetary equilibrium temperature [K]
T_eff = (
    T_eq / (1-A)**0.25 * np.sqrt(2 * a_Rsun / Rs)
)

# Store result in Kelvin
T_eff = experiment_4.loc[mask, "stellar_effective_temp_k"]

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_equil_temp_k         26.90%
planet_rad_earth_rad        24.91%
stellar_rad_solar_rad        9.98%
stellar_surf_grav            8.17%
stellar_effective_temp_k     7.68%
orbital_period_day           0.44%
stellar_mass_solar_mass      0.41%
orbit_semi_major_axis_au     0.18%
star_number_per_system       0.00%
planet_name                  0.00%
dtype: object

In [ ]:
# imputing for missing value for plant equilibrium using Zero-Greenhouse Equilibrium Temperature of Exoplanet Equation

# For: T_eq = T_eff * (1 - A)^(1/4) * sqrt(Rs/(2a)) where Rs is the stellar radius in sun radius and a is the orbital semi major axis (coverted from AU to Solar Radius)
# and T_eff is the stellar effective temperature

# Constants
AU_to_Rsun = 215.032    # 1 AU = 215.032 solar radii
A = 0.5                 # Bond albedo (assumed A = 0.5 neither hihgly reflective nor completely dark)

# Valid inputs: stellar temperature [K], stellar radius [R_sun], semi-major axis [AU]
valid_inputs = (
    experiment_4["stellar_effective_temp_k"].notna() &
    experiment_4["stellar_rad_solar_rad"].notna() &
    experiment_4["orbit_semi_major_axis_au"].notna() &
    (experiment_4["stellar_effective_temp_k"] > 0) &
    (experiment_4["stellar_rad_solar_rad"] > 0) &
    (experiment_4["orbit_semi_major_axis_au"] > 0)
)

# Mask rows where planetary equilibrium temperature is missing
mask = experiment_4["planet_equil_temp_k"].isna() & valid_inputs

# Stellar effective temperature already in Kelvin
T_eff = experiment_4.loc[mask, "stellar_effective_temp_k"]

# Convert semi-major axis from AU to sun radius since Rs/a must be dimensionless
a_Rsun = (
    experiment_4.loc[mask, "orbit_semi_major_axis_au"] * AU_to_Rsun
)

# Stellar radius already in sun radius
Rs = experiment_4.loc[mask, "stellar_rad_solar_rad"]

# Compute planetary equilibrium temperature [K]
T_eq = (
    T_eff *
    (1 - A) ** 0.25 *
    np.sqrt(Rs / (2 * a_Rsun))
)

# Store result in Kelvin
experiment_4.loc[mask, "planet_equil_temp_k"] = T_eq

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_rad_earth_rad        24.91%
stellar_rad_solar_rad        9.98%
planet_equil_temp_k          9.55%
stellar_surf_grav            8.17%
stellar_effective_temp_k     7.68%
orbital_period_day           0.44%
stellar_mass_solar_mass      0.41%
orbit_semi_major_axis_au     0.18%
star_number_per_system       0.00%
planet_name                  0.00%
dtype: object

* planet radius missing values cant be imputed since the planet mass feature was removed due its large percentage of missing data
* stellar radius and stellar mass missing values cannot be imputed since no current astronomical equation is available to impute for them

#### Creating relavent columns

In [ ]:
# Creating stellar luminosity Using the Stefan-Boltzmann Formula

# For Ls = Rs^(2) * Teff_s^(4) where Ls is the stellar luminosity (in terms of sun's luminosity), Rs is the stellar radius (in terms of sun;s radius), and
# Ts is the stellar effective surface temperature (in terms of sun's effective surface temperature)

# Constants and conversion factors
# sun's effective surface temperature in Kelvin [K]
Teff_sun = 5778 #K

# valid calculation if stellar radius and stellar effective temperature is known
mask_lum = (
    experiment_4["stellar_rad_solar_rad"].notna() &
    experiment_4["stellar_effective_temp_k"].notna()
)

# converting the stellar effective surface temperature in Kelvin to Sun's effective surface temperature in Kelvin
Teff_s = experiment_4.loc[mask, "stellar_effective_temp_k"] / Teff_sun

experiment_4.loc[mask_lum, "stellar_luminosity_solar_lum"] = (
    experiment_4.loc[mask_lum, "stellar_rad_solar_rad"]**2 *
    (experiment_4.loc[mask_lum, "stellar_effective_temp_k"] / Teff_sun)**4
)

# fill remaining rows with NaN (pandas does this by default)
experiment_4["stellar_luminosity_solar_lum"] = experiment_4["stellar_luminosity_solar_lum"].astype(float)

In [ ]:
# Creating Planet Radial Velocity Column Using Planet Radial Velocity Formula

# For: v_orb = sqrt(G * Ms / a), expressed in units of Earth's orbital velocity
# Ms = stellar mass [M_sun], a = semi-major axis [AU]

# Constants
G = 6.67430e-11        # m^3 kg^-1 s^-2
M_sun = 1.98847e30     # kg
AU = 1.495978707e11    # m
v_earth_km_s = 29.78   # Earth's orbital velocity in km/s

# valid calculation if stellar mass and semi-major axis are known
mask_vel = (
    experiment_4["stellar_mass_solar_mass"].notna() &
    experiment_4["orbit_semi_major_axis_au"].notna()
)

# convert to SI units
M_star = experiment_4.loc[mask_vel, "stellar_mass_solar_mass"] * M_sun
a_m = experiment_4.loc[mask_vel, "orbit_semi_major_axis_au"] * AU

# compute orbital velocity [m/s]
v_orb_m_s = np.sqrt(G * M_star / a_m)

# convert to km/s
v_orb_km_s = v_orb_m_s / 1e3

# convert to Earth orbital velocity units
v_orb_earth_units = v_orb_km_s / v_earth_km_s

# store result in new column
experiment_4.loc[mask_vel, "planet_orbital_velocity"] = v_orb_earth_units

# ensure column is float
experiment_4["planet_orbital_velocity"] = experiment_4["planet_orbital_velocity"].astype(float)

* The habitable zone binary column cannot be created since the spectral type feature was removed due to their significant percentage of missing data

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_rad_earth_rad            24.91%
stellar_luminosity_solar_lum    10.38%
stellar_rad_solar_rad            9.98%
planet_equil_temp_k              9.55%
stellar_surf_grav                8.17%
stellar_effective_temp_k         7.68%
planet_orbital_velocity          0.51%
orbital_period_day               0.44%
stellar_mass_solar_mass          0.41%
orbit_semi_major_axis_au         0.18%
planet_name                      0.00%
star_number_per_system           0.00%
dtype: object

#### Removing Rows (Exoplanets) With Significant Missing Data

In [ ]:
# removing rows where orbit_semi_major_axis_au is still missing
experiment_4 = experiment_4[~experiment_4["orbit_semi_major_axis_au"].isna()]
experiment_4.shape

(6060, 12)

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_rad_earth_rad            24.77%
stellar_luminosity_solar_lum    10.21%
stellar_rad_solar_rad            9.82%
planet_equil_temp_k              9.39%
stellar_surf_grav                8.05%
stellar_effective_temp_k         7.56%
stellar_mass_solar_mass          0.33%
orbital_period_day               0.33%
planet_orbital_velocity          0.33%
orbit_semi_major_axis_au         0.00%
planet_name                      0.00%
star_number_per_system           0.00%
dtype: object

In [ ]:
# removing rows where stellar_mass_solar_mass is still missing
experiment_4 = experiment_4[~experiment_4["stellar_mass_solar_mass"].isna()]
experiment_4.shape

(6040, 12)

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_rad_earth_rad            24.62%
stellar_luminosity_solar_lum     9.98%
stellar_rad_solar_rad            9.59%
planet_equil_temp_k              9.34%
stellar_surf_grav                7.75%
stellar_effective_temp_k         7.37%
star_number_per_system           0.00%
planet_name                      0.00%
orbit_semi_major_axis_au         0.00%
orbital_period_day               0.00%
stellar_mass_solar_mass          0.00%
planet_orbital_velocity          0.00%
dtype: object

In [ ]:
# removing rows where stellar_effective_temp_k is still missing
experiment_4 = experiment_4[~experiment_4["stellar_effective_temp_k"].isna()]
experiment_4.shape

(5595, 12)

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_rad_earth_rad            19.02%
stellar_rad_solar_rad            2.82%
stellar_luminosity_solar_lum     2.82%
planet_equil_temp_k              2.56%
stellar_surf_grav                0.86%
orbital_period_day               0.00%
star_number_per_system           0.00%
planet_name                      0.00%
orbit_semi_major_axis_au         0.00%
stellar_effective_temp_k         0.00%
stellar_mass_solar_mass          0.00%
planet_orbital_velocity          0.00%
dtype: object

In [ ]:
# removing rows where stellar_surf_grav is still missing
experiment_4 = experiment_4[~experiment_4["stellar_surf_grav"].isna()]
experiment_4.shape

(5547, 12)

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_rad_earth_rad            18.33%
stellar_rad_solar_rad            1.98%
stellar_luminosity_solar_lum     1.98%
planet_equil_temp_k              1.80%
orbit_semi_major_axis_au         0.00%
orbital_period_day               0.00%
star_number_per_system           0.00%
planet_name                      0.00%
stellar_effective_temp_k         0.00%
stellar_mass_solar_mass          0.00%
stellar_surf_grav                0.00%
planet_orbital_velocity          0.00%
dtype: object

In [ ]:
# removing rows where stellar_rad_solar_rad is still missing
experiment_4 = experiment_4[~experiment_4["stellar_rad_solar_rad"].isna()]
experiment_4.shape

(5437, 12)

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_rad_earth_rad            16.77%
planet_name                      0.00%
orbital_period_day               0.00%
star_number_per_system           0.00%
orbit_semi_major_axis_au         0.00%
planet_equil_temp_k              0.00%
stellar_effective_temp_k         0.00%
stellar_rad_solar_rad            0.00%
stellar_mass_solar_mass          0.00%
stellar_surf_grav                0.00%
stellar_luminosity_solar_lum     0.00%
planet_orbital_velocity          0.00%
dtype: object

In [ ]:
# crating a copy of the dataset
experiment_4_no_plan_rad = experiment_4.drop(columns=['planet_rad_earth_rad'])

In [ ]:
# removing rows where planet_rad_earth_rad is still missing
experiment_4 = experiment_4[~experiment_4["planet_rad_earth_rad"].isna()]
experiment_4.shape

(4525, 12)

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4.isnull().sum() / len(experiment_4))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_name                     0.00%
star_number_per_system          0.00%
orbital_period_day              0.00%
orbit_semi_major_axis_au        0.00%
planet_rad_earth_rad            0.00%
planet_equil_temp_k             0.00%
stellar_effective_temp_k        0.00%
stellar_rad_solar_rad           0.00%
stellar_mass_solar_mass         0.00%
stellar_surf_grav               0.00%
stellar_luminosity_solar_lum    0.00%
planet_orbital_velocity         0.00%
dtype: object

4,525 exoplanets remain with 12 key features where the features:
planet mass, spectral type, and habitable zone are no longer included in the key features since they were either the initial features which were removed due to a large amount of missing values or they could not be created.

In [ ]:
experiment_4_no_plan_rad.shape

(5437, 11)

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_4_no_plan_rad.isnull().sum() / len(experiment_4_no_plan_rad))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_name                     0.00%
star_number_per_system          0.00%
orbital_period_day              0.00%
orbit_semi_major_axis_au        0.00%
planet_equil_temp_k             0.00%
stellar_effective_temp_k        0.00%
stellar_rad_solar_rad           0.00%
stellar_mass_solar_mass         0.00%
stellar_surf_grav               0.00%
stellar_luminosity_solar_lum    0.00%
planet_orbital_velocity         0.00%
dtype: object

5,437 exoplanets remain with 11 key features where the features: planet radius, planet mass, spectral type, and habitable zone are no longer included in the key features since they were either the initial features which were removed due to a large amount of missing values or they could not be created.

#### Preparing dataset for modeling

In [ ]:
# Ensuring all features are normalized to be in terms of earth's and the sun's features

# Normalize the orbital period column
experiment_4['orbital_period_day'] = experiment_4['orbital_period_day'] / 365.26
# Normalize the planet equilibrium temperature
experiment_4['planet_equil_temp_k'] = experiment_4['planet_equil_temp_k'] / 255.0
# Normalize the stellar effective temperature
experiment_4['stellar_effective_temp_k'] = experiment_4['stellar_effective_temp_k'] / 5772.0

# Normalize the orbital period column
experiment_4_no_plan_rad['orbital_period_day'] = experiment_4_no_plan_rad['orbital_period_day'] / 365.26
# Normalize the planet equilibrium temperature
experiment_4_no_plan_rad['planet_equil_temp_k'] = experiment_4_no_plan_rad['planet_equil_temp_k'] / 255.0
# Normalize the stellar effective temperature
experiment_4_no_plan_rad['stellar_effective_temp_k'] = experiment_4_no_plan_rad['stellar_effective_temp_k'] / 5772.0

In [ ]:
experiment_4.columns

Index(['planet_name', 'star_number_per_system', 'orbital_period_day',
       'orbit_semi_major_axis_au', 'planet_rad_earth_rad',
       'planet_equil_temp_k', 'stellar_effective_temp_k',
       'stellar_rad_solar_rad', 'stellar_mass_solar_mass', 'stellar_surf_grav',
       'stellar_luminosity_solar_lum', 'planet_orbital_velocity'],
      dtype='object')

In [ ]:
# creating a target row called Earth which all the other rows will be compared to (similarity search)
earth_experiment_4 = pd.DataFrame({'planet_name': ['Earth'],
                                   'star_number_per_system': [1.0],
                                    'orbital_period_day': [1.0],
                                    'orbit_semi_major_axis_au':[1.0],
                                    'planet_rad_earth_rad': [1.0],
                                    'planet_equil_temp_k': [1.0],
                                    'stellar_effective_temp_k': [1.0],
                                    'stellar_rad_solar_rad': [1.0],
                                    'stellar_mass_solar_mass': [1.0],
                                    'stellar_surf_grav': [1.0],
                                    'stellar_luminosity_solar_lum': [1.0],
                                    'planet_orbital_velocity': [1.0]})
earth_experiment_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   planet_name                   1 non-null      object
 1   star_number_per_system        1 non-null      float64
 2   orbital_period_day            1 non-null      float64
 3   orbit_semi_major_axis_au      1 non-null      float64
 4   planet_rad_earth_rad          1 non-null      float64
 5   planet_equil_temp_k           1 non-null      float64
 6   stellar_effective_temp_k      1 non-null      float64
 7   stellar_rad_solar_rad         1 non-null      float64
 8   stellar_mass_solar_mass       1 non-null      float64
 9   stellar_surf_grav             1 non-null      float64
 10  stellar_luminosity_solar_lum  1 non-null      float64
 11  planet_orbital_velocity       1 non-null      float64
dtypes: float64(11), object(1)
memory usage: 228.0+ bytes

In [ ]:
earth_experiment_4_no_plan_rad = pd.DataFrame({'planet_name': ['Earth'],
                                                'star_number_per_system': [1.0],
                                                'orbital_period_day': [1.0],
                                                'orbit_semi_major_axis_au':[1.0],
                                                'planet_equil_temp_k': [1.0],
                                                'stellar_effective_temp_k': [1.0],
                                                'stellar_rad_solar_rad': [1.0],
                                                'stellar_mass_solar_mass': [1.0],
                                                'stellar_surf_grav': [1.0],
                                                'stellar_luminosity_solar_lum': [1.0],
                                                'planet_orbital_velocity': [1.0]})
earth_experiment_4_no_plan_rad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   planet_name                   1 non-null      object
 1   star_number_per_system        1 non-null      float64
 2   orbital_period_day            1 non-null      float64
 3   orbit_semi_major_axis_au      1 non-null      float64
 4   planet_equil_temp_k           1 non-null      float64
 5   stellar_effective_temp_k      1 non-null      float64
 6   stellar_rad_solar_rad         1 non-null      float64
 7   stellar_mass_solar_mass       1 non-null      float64
 8   stellar_surf_grav             1 non-null      float64
 9   stellar_luminosity_solar_lum  1 non-null      float64
 10  planet_orbital_velocity       1 non-null      float64
dtypes: float64(10), object(1)
memory usage: 220.0+ bytes

In [ ]:
# setting the planet name as the index

# set planet name as index for earth row
earth_experiment_4.set_index('planet_name', inplace=True)
earth_experiment_4_no_plan_rad.set_index('planet_name', inplace=True)

# setting the planet_name as the index
experiment_4.set_index('planet_name', inplace=True)
experiment_4_no_plan_rad.set_index('planet_name', inplace=True)

#### No encoding needed since spectral column removed

#### Applying the weights from our proposed method

In [ ]:
# Define weights (same order as columns)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 7.0,
    'orbit_semi_major_axis_au': 6.0,
    'planet_rad_earth_rad': 5.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 6.0,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.5,
    'stellar_mass_solar_mass': 1.5,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 7.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 7.0,
}

# Apply weights
for col in experiment_4.columns:
    weight = weights.get(col, 1.0)
    experiment_4[col] *= weight
    earth_experiment_4[col] *= weight

# Apply weights (with no planet radius)
for col in experiment_4_no_plan_rad.columns:
    weight = weights.get(col, 1.0)
    experiment_4_no_plan_rad[col] *= weight
    earth_experiment_4_no_plan_rad[col] *= weight

## **Weighted Reduced Features Method Manhattan KNN Model #41**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_4)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_experiment_4)

# Retrieve the 10 closest planet names
closest_planets_man20 = experiment_4.index[indices[0]].tolist()
closest_distances_man20 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man20[i]} (Distance: {closest_distances_man20[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 7.8522)
2. Kepler-62 f (Distance: 12.5816)
3. Kepler-22 b (Distance: 12.7885)
4. Kepler-1638 b (Distance: 13.0252)
5. Kepler-69 c (Distance: 13.0697)
6. Kepler-1632 b (Distance: 13.3384)
7. Kepler-1126 c (Distance: 13.4551)
8. Kepler-311 d (Distance: 15.1160)
9. Kepler-289 e (Distance: 15.2893)
10. Kepler-1544 b (Distance: 15.7265)

## **Weighted Reduced Features Method Euclidean KNN Model #42**

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_4)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_experiment_4)

# Retrieve the 10 closest planet names
closest_planets_euc20 = experiment_4.index[indices[0]].tolist()
closest_distances_euc20 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc20[i]} (Distance: {closest_distances_euc20[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 4.7120)
2. Kepler-62 f (Distance: 5.2429)
3. Kepler-1126 c (Distance: 6.0478)
4. Kepler-1638 b (Distance: 6.1687)
5. Kepler-69 c (Distance: 6.2009)
6. Kepler-441 b (Distance: 6.8481)
7. Kepler-1544 b (Distance: 7.0696)
8. Kepler-311 d (Distance: 7.0943)
9. Kepler-22 b (Distance: 7.1336)
10. Kepler-1632 b (Distance: 7.1636)

model #43 (no planet radius)

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_4_no_plan_rad)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_experiment_4_no_plan_rad)

# Retrieve the 10 closest planet names
closest_planets_man21 = experiment_4_no_plan_rad.index[indices[0]].tolist()
closest_distances_man21 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man21[i]} (Distance: {closest_distances_man21[i]:.4f})")

Top 10 most similar planets:
1. Kepler-139 f (Distance: 4.4509)
2. Kepler-452 b (Distance: 4.7022)
3. HD 28185 b (Distance: 4.7930)
4. HD 100777 b (Distance: 4.8831)
5. HD 142415 b (Distance: 4.9684)
6. HD 108874 b (Distance: 5.0696)
7. Kepler-1634 b (Distance: 5.0860)
8. HD 92788 b (Distance: 5.1074)
9. HD 43197 b (Distance: 5.5789)
10. Kepler-289 e (Distance: 5.5893)

model #44 (no planet radius)

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_4_no_plan_rad)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_experiment_4_no_plan_rad)

# Retrieve the 10 closest planet names
closest_planets_euc21 = experiment_4_no_plan_rad.index[indices[0]].tolist()
closest_distances_euc21 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc21[i]} (Distance: {closest_distances_euc21[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1634 b (Distance: 3.4331)
2. HD 100777 b (Distance: 3.4550)
3. Kepler-139 f (Distance: 3.4809)
4. HD 108874 b (Distance: 3.5039)
5. Kepler-452 b (Distance: 3.5043)
6. HD 92788 b (Distance: 3.5076)
7. HD 43197 b (Distance: 3.5169)
8. HD 28185 b (Distance: 3.5429)
9. HD 142415 b (Distance: 3.5490)
10. Kepler-289 e (Distance: 3.5552)

### **Complete-case dataset: only include planets that originally had complete values for the key ranking features before imputation**

In [ ]:
experiment_5.shape

(6071, 12)

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_5.isnull().sum() / len(experiment_5))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

spectral_type               68.57%
planet_mass_earth_mass      47.62%
planet_equil_temp_k         26.90%
planet_rad_earth_rad        24.91%
stellar_surf_grav           10.69%
stellar_rad_solar_rad        9.98%
stellar_effective_temp_k     7.68%
orbital_period_day           5.24%
orbit_semi_major_axis_au     5.09%
stellar_mass_solar_mass      0.66%
planet_name                  0.00%
star_number_per_system       0.00%
dtype: object

In [ ]:
experiment_5.columns

Index(['planet_name', 'star_number_per_system', 'spectral_type',
       'orbital_period_day', 'orbit_semi_major_axis_au',
       'planet_rad_earth_rad', 'planet_mass_earth_mass', 'planet_equil_temp_k',
       'stellar_effective_temp_k', 'stellar_rad_solar_rad',
       'stellar_mass_solar_mass', 'stellar_surf_grav'],
      dtype='object')

In [ ]:
required_features = [
    'planet_name',
    'star_number_per_system',
    'spectral_type',
    'orbital_period_day',
    'orbit_semi_major_axis_au',
    'planet_rad_earth_rad',
    'planet_mass_earth_mass',
    'planet_equil_temp_k',
    'stellar_effective_temp_k',
    'stellar_rad_solar_rad',
    'stellar_mass_solar_mass',
    'stellar_surf_grav'
]

# create mask for rows with no missing values in required features
mask = experiment_5[required_features].notna().all(axis=1)

# apply the same mask to experiment_5
experiment_5_complete_only = experiment_5[mask].copy()

In [ ]:
# Viewing the percentage of missing value for each column
missing_percentage = (experiment_5_complete_only.isnull().sum() / len(experiment_5_complete_only))
((missing_percentage * 100).sort_values(ascending=False)).map(lambda x: f"{x:.2f}%")

planet_name                 0.00%
star_number_per_system      0.00%
spectral_type               0.00%
orbital_period_day          0.00%
orbit_semi_major_axis_au    0.00%
planet_rad_earth_rad        0.00%
planet_mass_earth_mass      0.00%
planet_equil_temp_k         0.00%
stellar_effective_temp_k    0.00%
stellar_rad_solar_rad       0.00%
stellar_mass_solar_mass     0.00%
stellar_surf_grav           0.00%
dtype: object

In [ ]:
experiment_5_complete_only.info()

<class 'pandas.core.frame.DataFrame'>
Index: 758 entries, 36 to 6053
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   planet_name               758 non-null    object
 1   star_number_per_system    758 non-null    float64
 2   spectral_type             758 non-null    object
 3   orbital_period_day        758 non-null    float64
 4   orbit_semi_major_axis_au  758 non-null    float64
 5   planet_rad_earth_rad      758 non-null    float64
 6   planet_mass_earth_mass    758 non-null    float64
 7   planet_equil_temp_k       758 non-null    float64
 8   stellar_effective_temp_k  758 non-null    float64
 9   stellar_rad_solar_rad     758 non-null    float64
 10  stellar_mass_solar_mass   758 non-null    float64
 11  stellar_surf_grav         758 non-null    float64
dtypes: float64(10), object(2)
memory usage: 77.0+ KB

In [ ]:
experiment_5_complete_only.shape

(758, 12)

In [ ]:
# rows with at least one missing value
rows_with_missing = experiment_5[experiment_5[required_features].isna().any(axis=1)]
rows_with_missing.shape

(5313, 12)

#### Creating relavent columns

In [ ]:
# Creating stellar luminosity Using the Stefan-Boltzmann Formula

# For Ls = Rs^(2) * Teff_s^(4) where Ls is the stellar luminosity (in terms of sun's luminosity), Rs is the stellar radius (in terms of sun;s radius), and
# Ts is the stellar effective surface temperature (in terms of sun's effective surface temperature)

# Constants and conversion factors
# sun's effective surface temperature in Kelvin [K]
Teff_sun = 5778 #K

# valid calculation if stellar radius and stellar effective temperature is known
mask_lum = (
    experiment_5_complete_only["stellar_rad_solar_rad"].notna() &
    experiment_5_complete_only["stellar_effective_temp_k"].notna()
)

# converting the stellar effective surface temperature in Kelvin to Sun's effective surface temperature in Kelvin
Teff_s = experiment_5_complete_only.loc[mask, "stellar_effective_temp_k"] / Teff_sun

experiment_5_complete_only.loc[mask_lum, "stellar_luminosity_solar_lum"] = (
    experiment_5_complete_only.loc[mask_lum, "stellar_rad_solar_rad"]**2 *
    (experiment_5_complete_only.loc[mask_lum, "stellar_effective_temp_k"] / Teff_sun)**4
)

# fill remaining rows with NaN (pandas does this by default)
experiment_5_complete_only["stellar_luminosity_solar_lum"] = experiment_5_complete_only["stellar_luminosity_solar_lum"].astype(float)

In [ ]:
# Creating Planet Radial Velocity Column Using Planet Radial Velocity Formula

# For: v_orb = sqrt(G * Ms / a), expressed in units of Earth's orbital velocity
# Ms = stellar mass [M_sun], a = semi-major axis [AU]

# Constants
G = 6.67430e-11        # m^3 kg^-1 s^-2
M_sun = 1.98847e30     # kg
AU = 1.495978707e11    # m
v_earth_km_s = 29.78   # Earth's orbital velocity in km/s

# valid calculation if stellar mass and semi-major axis are known
mask_vel = (
    experiment_5_complete_only["stellar_mass_solar_mass"].notna() &
    experiment_5_complete_only["orbit_semi_major_axis_au"].notna()
)

# convert to SI units
M_star = experiment_5_complete_only.loc[mask_vel, "stellar_mass_solar_mass"] * M_sun
a_m = experiment_5_complete_only.loc[mask_vel, "orbit_semi_major_axis_au"] * AU

# compute orbital velocity [m/s]
v_orb_m_s = np.sqrt(G * M_star / a_m)

# convert to km/s
v_orb_km_s = v_orb_m_s / 1e3

# convert to Earth orbital velocity units
v_orb_earth_units = v_orb_km_s / v_earth_km_s

# store result in new column
experiment_5_complete_only.loc[mask_vel, "planet_orbital_velocity"] = v_orb_earth_units

# ensure column is float
experiment_5_complete_only["planet_orbital_velocity"] = experiment_5_complete_only["planet_orbital_velocity"].astype(float)

#### Fixing Inconsistencies within Spectral Type Column

In [ ]:
cols_to_show6 = [
    "planet_name", # Changed from "host_star_name" as it's not present in experiment_5_complete_only
    "spectral_type",
    "star_number_per_system",
    "stellar_effective_temp_k",
    "stellar_mass_solar_mass",
    "stellar_rad_solar_rad",
    "stellar_luminosity_solar_lum" # stellar_mass_imputation_method removed as it's not present
]

# Finding the entries in the spectral_type column which contain \ or / or - or +
# r is known as raw string and it treats the backslashes inside the string literally and not as escape characters. Without the r, you'd need to double the backslashes (e.g., \\)
# na=False handles the missing entries
contains_dash_or_slash_df = experiment_5_complete_only[experiment_5_complete_only['spectral_type'].str.contains(r'[\/\\\-+\-]', na=False)][cols_to_show6]

# List out the filtered entries
print("Entries that contain '\\' or /' or '-' or '+:")
print(contains_dash_or_slash_df)

# Get the count of such entries
count = len(contains_dash_or_slash_df)
print(f"Count of entries that contain '\\' or '/' or '-' or '+': {count} entries")

Entries that contain '\' or /' or '-' or '+:
           planet_name     spectral_type  star_number_per_system  \
97    CFHTWIR-Oph 98 b             M9-L1                     1.0
191   EPIC 249893012 b           G8 IV/V                     1.0
192   EPIC 249893012 c           G8 IV/V                     1.0
193   EPIC 249893012 d           G8 IV/V                     1.0
851        HD 189733 b            K0-2 V                     2.0
1636          K2-261 b           G7 IV/V                     1.0
1921          KELT-9 b           B9.5-A0                     2.0
3680      Kepler-278 b         K2 III-IV                     1.0
3681      Kepler-278 c         K2 III-IV                     1.0
3995      Kepler-391 b         K2 III-IV                     1.0
3996      Kepler-391 c         K2 III-IV                     1.0
4871       LP 791-18 c    M(6.1+/-0.7) V                     1.0
4872       LP 791-18 d  M(6.1 +/- 0.7) V                     1.0
5143        TOI-1075 b         K9 V/M0 V                     1.0
5176        TOI-1238 b             K7/M0                     1.0
5177        TOI-1238 c             K7/M0                     1.0
5243        TOI-1452 b      M4 +/- 0.5 V                     2.0
5315        TOI-1801 b      M0.5+/-0.5 V                     2.0
5366        TOI-2095 b        M0.5-1.0 V                     1.0
5367        TOI-2095 c        M0.5-1.0 V                     1.0
5435        TOI-2458 b           F9-F9.5                     1.0
5490        TOI-3261 b          K1.5+/-1                     1.0
5525      TOI-3984 A b          M4+/-0.5                     2.0
5533         TOI-411 b            F7/F8V                     1.0
5534         TOI-411 c            F7/F8V                     1.0
5541        TOI-4201 b        M1.0+/-0.5                     1.0
5571        TOI-4515 b             G8/G9                     1.0
5621      TOI-5293 A b            M3+/-1                     2.0
5657        TOI-5720 b      M3.5 +/- 1.0                     1.0
5667        TOI-5817 b           G2 IV-V                     2.0
5705        TOI-6695 b           F5V-G0V                     1.0
5745         TOI-837 b           G0/F9 V                     1.0
5884        WASP-178 b           A1 IV-V                     1.0
5898        WASP-190 b           F6 IV-V                     1.0

      stellar_effective_temp_k  stellar_mass_solar_mass  \
97                 2320.000000                 0.014700
191                5430.000000                 1.050000
192                5430.000000                 1.050000
193                5430.000000                 1.050000
851                5014.433333                 0.828985
1636               5508.000000                 1.098857
1921              10170.000000                 2.520000
3680               4977.082857                 1.280250
3681               4977.082857                 1.280250
3995               5107.196667                 1.265286
3996               5092.045000                 1.309800
4871               2960.000000                 0.139000
4872               2960.000000                 0.139000
5143               3898.000000                 0.602000
5176               4089.000000                 0.590000
5177               4089.000000                 0.590000
5243               3185.000000                 0.249000
5315               3805.500000                 0.530550
5366               3710.500000                 0.452500
5367               3710.500000                 0.452500
5435               6005.000000                 1.050000
5490               5068.000000                 0.861000
5525               3476.000000                 0.490000
5533               6104.500000                 1.101000
5534               6104.500000                 1.101000
5541               3858.500000                 0.619000
5571               5433.000000                 0.949000
5621               3586.000000                 0.508000
5657               3325.000000                 0.383000
5667               5770.000000                 0.970000
5705               6400.000000                 1.338000
5745               6027.200000                 1.124000
5884               9000.000000                 2.000000
5898               6400.000000                 1.350000

      stellar_rad_solar_rad  stellar_luminosity_solar_lum
97                 0.245000                      0.001560
191                1.710000                      2.280769
192                1.710000                      2.280769
193                1.710000                      2.280769
851                0.765666                      0.332549
1636               1.655500                      2.263205
1921               2.362000                     53.546791
3680               2.916954                      4.684340
3681               2.916954                      4.684340
3995               2.682410                      4.392083
3996               2.689158                      4.362057
4871               0.174667                      0.002101
4872               0.182000                      0.002281
5143               0.580500                      0.069801
5176               0.580000                      0.084375
5177               0.580000                      0.084375
5243               0.275000                      0.006982
5315               0.547000                      0.056300
5366               0.446500                      0.033905
5367               0.446500                      0.033905
5435               1.310000                      2.002094
5490               0.849000                      0.426630
5525               0.470000                      0.028934
5533               1.117000                      1.554521
5534               1.117000                      1.554521
5541               0.624000                      0.077434
5571               0.860000                      0.578157
5621               0.520000                      0.040118
5657               0.383000                      0.016086
5667               1.427000                      2.025075
5705               1.517000                      3.464024
5745               1.030800                      1.258059
5884               1.670000                     16.416963
5898               1.600000                      3.853450
Count of entries that contain '\' or '/' or '-' or '+': 34 entries

In [ ]:
experiment_5_complete_only['spectral_type'].unique()

array(['G8 V', 'M1', 'G', 'M9-L1', 'M3 V', 'G0 V', 'K1 V', 'F6 V', 'F9 V',
       'G2 V', 'G9 V', 'G3 V', 'F9', 'G5', 'G2', 'F3 V', 'G0 VI', 'G0',
       'F5 V', 'G8 IV/V', 'M2.5 V', 'M4.5 V', 'M4 V', 'K4.5', 'M2 V',
       'M1.5', 'M1.0 V', 'M3.5 V', 'K7 V', 'M1.5 V', 'K6 V', 'F2',
       'M3.0 V', 'K4', 'G4', 'F', 'F8', 'K', 'K2', 'K1', 'K3', 'G3', 'F4',
       'G5 V', 'A8 V', 'G V', 'K V', 'F V', 'G6 V', 'M1 V', 'K0.0 V',
       'K0', 'G4 V', 'K2 V', 'K0-2 V', 'K2.5 V', 'K0 V', 'K3 V', 'K4 V',
       'M0 V', 'F5', 'G1 V', 'K0.5 V', 'A5 V', 'A5', 'F9 IV', 'K5.5',
       'K5 V', 'M4.5', 'G7 IV/V', 'G7 V', 'M3', 'M5 V', 'M V', 'F8 V',
       'G0 IV', 'F7 V', 'A', 'F4 V', 'A2 V', 'F7', 'B9.5-A0', 'F9V',
       'G3 IV', 'F6 IV', 'K2 III-IV', 'F7 IV', 'F5 IV', 'M', 'G2 IV',
       'K5', 'm3 V', 'M0.0 V', 'M(6.1+/-0.7) V', 'M(6.1 +/- 0.7) V',
       'M6 V', 'M3.0', 'A8', 'A7 V', 'M0.5', 'G1 IV', 'K9 V/M0 V', 'K7',
       'G9', 'M2.0 V', 'M0.5 V', 'K7/M0', 'M2', 'G5V', 'Am C',
       'M4 +/- 0.5 V', 'F0', 'G9 IV', 'M5V', 'M0', 'M0.5+/-0.5 V', 'M4',
       'M0.5-1.0 V', 'K2V', 'F9-F9.5', 'K8 V', 'K1.5+/-1', 'M4+/-0.5',
       'F7/F8V', 'M1.0+/-0.5', 'G8/G9', 'M4.0', 'M3+/-1', 'M3.5 +/- 1.0',
       'G2 IV-V', 'M5.0', 'G7', 'F2 V', 'F5V-G0V', 'G0/F9 V', 'M8.0 V',
       'F6', 'G8', 'K6', 'G1', 'G6', 'F1 V', 'A1 IV-V', 'F6 IV-V',
       'K3.5 V', 'F5V'], dtype=object)

In [ ]:
# IV/V becomes IV
# IV-V becomes IV
# III-IV becomes III
# III/IV becomes III
# II-III becomes II

experiment_5_complete_only.loc[:, 'spectral_type'] = (
    experiment_5_complete_only['spectral_type']
    .str.replace(
        r'\b(VII|VI|IV|V|III|II|I)(?:[\/-](VII|VI|IV|V|III|II|I))\b',
        r'\1',
        regex=True
    )
)

In [ ]:
# checking if these changes were made to the spectral type column
experiment_5_complete_only['spectral_type'].unique()

array(['G8 V', 'M1', 'G', 'M9-L1', 'M3 V', 'G0 V', 'K1 V', 'F6 V', 'F9 V',
       'G2 V', 'G9 V', 'G3 V', 'F9', 'G5', 'G2', 'F3 V', 'G0 VI', 'G0',
       'F5 V', 'G8 IV', 'M2.5 V', 'M4.5 V', 'M4 V', 'K4.5', 'M2 V',
       'M1.5', 'M1.0 V', 'M3.5 V', 'K7 V', 'M1.5 V', 'K6 V', 'F2',
       'M3.0 V', 'K4', 'G4', 'F', 'F8', 'K', 'K2', 'K1', 'K3', 'G3', 'F4',
       'G5 V', 'A8 V', 'G V', 'K V', 'F V', 'G6 V', 'M1 V', 'K0.0 V',
       'K0', 'G4 V', 'K2 V', 'K0-2 V', 'K2.5 V', 'K0 V', 'K3 V', 'K4 V',
       'M0 V', 'F5', 'G1 V', 'K0.5 V', 'A5 V', 'A5', 'F9 IV', 'K5.5',
       'K5 V', 'M4.5', 'G7 IV', 'G7 V', 'M3', 'M5 V', 'M V', 'F8 V',
       'G0 IV', 'F7 V', 'A', 'F4 V', 'A2 V', 'F7', 'B9.5-A0', 'F9V',
       'G3 IV', 'F6 IV', 'K2 III', 'F7 IV', 'F5 IV', 'M', 'G2 IV', 'K5',
       'm3 V', 'M0.0 V', 'M(6.1+/-0.7) V', 'M(6.1 +/- 0.7) V', 'M6 V',
       'M3.0', 'A8', 'A7 V', 'M0.5', 'G1 IV', 'K9 V/M0 V', 'K7', 'G9',
       'M2.0 V', 'M0.5 V', 'K7/M0', 'M2', 'G5V', 'Am C', 'M4 +/- 0.5 V',
       'F0', 'G9 IV', 'M5V', 'M0', 'M0.5+/-0.5 V', 'M4', 'M0.5-1.0 V',
       'K2V', 'F9-F9.5', 'K8 V', 'K1.5+/-1', 'M4+/-0.5', 'F7/F8V',
       'M1.0+/-0.5', 'G8/G9', 'M4.0', 'M3+/-1', 'M3.5 +/- 1.0', 'M5.0',
       'G7', 'F2 V', 'F5V-G0V', 'G0/F9 V', 'M8.0 V', 'F6', 'G8', 'K6',
       'G1', 'G6', 'F1 V', 'A1 IV', 'K3.5 V', 'F5V'], dtype=object)

In [ ]:
# checking which spectral type contains 'VII'
experiment_5_complete_only[experiment_5_complete_only["spectral_type"].str.contains("VII") == True][cols_to_show6]

Empty DataFrame
Columns: [planet_name, spectral_type, star_number_per_system, stellar_effective_temp_k, stellar_mass_solar_mass, stellar_rad_solar_rad, stellar_luminosity_solar_lum]
Index: []

In [ ]:
# checking which spectral type contains 'DC'
experiment_5_complete_only[experiment_5_complete_only["spectral_type"].str.contains("DC") == True][cols_to_show6]

Empty DataFrame
Columns: [planet_name, spectral_type, star_number_per_system, stellar_effective_temp_k, stellar_mass_solar_mass, stellar_rad_solar_rad, stellar_luminosity_solar_lum]
Index: []

In [ ]:
# checking which spectral type contains 'DQ'
experiment_5_complete_only[experiment_5_complete_only["spectral_type"].str.contains("DQ") == True][cols_to_show6]

Empty DataFrame
Columns: [planet_name, spectral_type, star_number_per_system, stellar_effective_temp_k, stellar_mass_solar_mass, stellar_rad_solar_rad, stellar_luminosity_solar_lum]
Index: []

In [ ]:
# checking which spectral type contains 'VI'
experiment_5_complete_only[experiment_5_complete_only["spectral_type"].str.contains("VI") == True][cols_to_show6]

,planet_name,spectral_type,star_number_per_system,stellar_effective_temp_k,stellar_mass_solar_mass,stellar_rad_solar_rad,stellar_luminosity_solar_lum
128,CoRoT-32 b,G0 VI,1.0,5970.0,1.08,0.79,0.711281

In [ ]:
# Replace luminosity class VI with SD (subdwarf)
experiment_5_complete_only.loc[:, "spectral_type"] = (
    experiment_5_complete_only["spectral_type"]
    .str.replace(r'.*VI.*', 'SD', regex=True)
)

In [ ]:
# checking which spectral type contains 'Vne'
experiment_5_complete_only[experiment_5_complete_only["spectral_type"].str.contains("Vne") == True][cols_to_show6]

Empty DataFrame
Columns: [planet_name, spectral_type, star_number_per_system, stellar_effective_temp_k, stellar_mass_solar_mass, stellar_rad_solar_rad, stellar_luminosity_solar_lum]
Index: []

In [ ]:
# checking which spectral type contains 'Ve'
experiment_5_complete_only[experiment_5_complete_only["spectral_type"].str.contains("Ve") == True][cols_to_show6]

Empty DataFrame
Columns: [planet_name, spectral_type, star_number_per_system, stellar_effective_temp_k, stellar_mass_solar_mass, stellar_rad_solar_rad, stellar_luminosity_solar_lum]
Index: []

In [ ]:
# checking which spectral type contains 'Am C'
experiment_5_complete_only[experiment_5_complete_only["spectral_type"].str.contains("Am C") == True][cols_to_show6]

,planet_name,spectral_type,star_number_per_system,stellar_effective_temp_k,stellar_mass_solar_mass,stellar_rad_solar_rad,stellar_luminosity_solar_lum
5231,TOI-1431 b,Am C,1.0,7690.0,1.9,1.92,11.566386

In [ ]:
# Replace luminosity class Am C with AV (Type A main sequence)
experiment_5_complete_only.loc[:, "spectral_type"] = (
    experiment_5_complete_only["spectral_type"]
    .str.replace(r'Am C', 'AV', regex=True)
)

In [ ]:
experiment_5_complete_only['spectral_type'].unique()

array(['G8 V', 'M1', 'G', 'M9-L1', 'M3 V', 'G0 V', 'K1 V', 'F6 V', 'F9 V',
       'G2 V', 'G9 V', 'G3 V', 'F9', 'G5', 'G2', 'F3 V', 'SD', 'G0',
       'F5 V', 'G8 IV', 'M2.5 V', 'M4.5 V', 'M4 V', 'K4.5', 'M2 V',
       'M1.5', 'M1.0 V', 'M3.5 V', 'K7 V', 'M1.5 V', 'K6 V', 'F2',
       'M3.0 V', 'K4', 'G4', 'F', 'F8', 'K', 'K2', 'K1', 'K3', 'G3', 'F4',
       'G5 V', 'A8 V', 'G V', 'K V', 'F V', 'G6 V', 'M1 V', 'K0.0 V',
       'K0', 'G4 V', 'K2 V', 'K0-2 V', 'K2.5 V', 'K0 V', 'K3 V', 'K4 V',
       'M0 V', 'F5', 'G1 V', 'K0.5 V', 'A5 V', 'A5', 'F9 IV', 'K5.5',
       'K5 V', 'M4.5', 'G7 IV', 'G7 V', 'M3', 'M5 V', 'M V', 'F8 V',
       'G0 IV', 'F7 V', 'A', 'F4 V', 'A2 V', 'F7', 'B9.5-A0', 'F9V',
       'G3 IV', 'F6 IV', 'K2 III', 'F7 IV', 'F5 IV', 'M', 'G2 IV', 'K5',
       'm3 V', 'M0.0 V', 'M(6.1+/-0.7) V', 'M(6.1 +/- 0.7) V', 'M6 V',
       'M3.0', 'A8', 'A7 V', 'M0.5', 'G1 IV', 'K9 V/M0 V', 'K7', 'G9',
       'M2.0 V', 'M0.5 V', 'K7/M0', 'M2', 'G5V', 'AV', 'M4 +/- 0.5 V',
       'F0', 'G9 IV', 'M5V', 'M0', 'M0.5+/-0.5 V', 'M4', 'M0.5-1.0 V',
       'K2V', 'F9-F9.5', 'K8 V', 'K1.5+/-1', 'M4+/-0.5', 'F7/F8V',
       'M1.0+/-0.5', 'G8/G9', 'M4.0', 'M3+/-1', 'M3.5 +/- 1.0', 'M5.0',
       'G7', 'F2 V', 'F5V-G0V', 'G0/F9 V', 'M8.0 V', 'F6', 'G8', 'K6',
       'G1', 'G6', 'F1 V', 'A1 IV', 'K3.5 V', 'F5V'], dtype=object)

In [ ]:
# removing all white space in spectral type column
experiment_5_complete_only["spectral_type"] = experiment_5_complete_only["spectral_type"].str.replace(r'\s+', '', regex=True)

In [ ]:
# checking if these changes were made to the spectral type column
experiment_5_complete_only['spectral_type'].unique()

array(['G8V', 'M1', 'G', 'M9-L1', 'M3V', 'G0V', 'K1V', 'F6V', 'F9V',
       'G2V', 'G9V', 'G3V', 'F9', 'G5', 'G2', 'F3V', 'SD', 'G0', 'F5V',
       'G8IV', 'M2.5V', 'M4.5V', 'M4V', 'K4.5', 'M2V', 'M1.5', 'M1.0V',
       'M3.5V', 'K7V', 'M1.5V', 'K6V', 'F2', 'M3.0V', 'K4', 'G4', 'F',
       'F8', 'K', 'K2', 'K1', 'K3', 'G3', 'F4', 'G5V', 'A8V', 'GV', 'KV',
       'FV', 'G6V', 'M1V', 'K0.0V', 'K0', 'G4V', 'K2V', 'K0-2V', 'K2.5V',
       'K0V', 'K3V', 'K4V', 'M0V', 'F5', 'G1V', 'K0.5V', 'A5V', 'A5',
       'F9IV', 'K5.5', 'K5V', 'M4.5', 'G7IV', 'G7V', 'M3', 'M5V', 'MV',
       'F8V', 'G0IV', 'F7V', 'A', 'F4V', 'A2V', 'F7', 'B9.5-A0', 'G3IV',
       'F6IV', 'K2III', 'F7IV', 'F5IV', 'M', 'G2IV', 'K5', 'm3V', 'M0.0V',
       'M(6.1+/-0.7)V', 'M6V', 'M3.0', 'A8', 'A7V', 'M0.5', 'G1IV',
       'K9V/M0V', 'K7', 'G9', 'M2.0V', 'M0.5V', 'K7/M0', 'M2', 'AV',
       'M4+/-0.5V', 'F0', 'G9IV', 'M0', 'M0.5+/-0.5V', 'M4', 'M0.5-1.0V',
       'F9-F9.5', 'K8V', 'K1.5+/-1', 'M4+/-0.5', 'F7/F8V', 'M1.0+/-0.5',
       'G8/G9', 'M4.0', 'M3+/-1', 'M3.5+/-1.0', 'M5.0', 'G7', 'F2V',
       'F5V-G0V', 'G0/F9V', 'M8.0V', 'F6', 'G8', 'K6', 'G1', 'G6', 'F1V',
       'A1IV', 'K3.5V'], dtype=object)

In [ ]:
# Remove all numbers and dots from spectral_type
experiment_5_complete_only["spectral_type"] = experiment_5_complete_only["spectral_type"].str.replace(r'[\d\.]+', '', regex=True)

In [ ]:
# checking if these changes were made to the spectral type column
experiment_5_complete_only['spectral_type'].unique()

array(['GV', 'M', 'G', 'M-L', 'MV', 'KV', 'FV', 'F', 'SD', 'GIV', 'K',
       'AV', 'K-V', 'A', 'FIV', 'B-A', 'KIII', 'mV', 'M(+/-)V', 'KV/MV',
       'K/M', 'M+/-V', 'M-V', 'F-F', 'K+/-', 'M+/-', 'F/FV', 'G/G',
       'FV-GV', 'G/FV', 'AIV'], dtype=object)

In [ ]:
# remove the special characters '+' from the entries
experiment_5_complete_only.loc[:, 'spectral_type'] = (experiment_5_complete_only["spectral_type"].str.replace(r'[+]', '', regex=True))

In [ ]:
# checking if these changes were made to the spectral type column
experiment_5_complete_only['spectral_type'].unique()

array(['GV', 'M', 'G', 'M-L', 'MV', 'KV', 'FV', 'F', 'SD', 'GIV', 'K',
       'AV', 'K-V', 'A', 'FIV', 'B-A', 'KIII', 'mV', 'M(/-)V', 'KV/MV',
       'K/M', 'M/-V', 'M-V', 'F-F', 'K/-', 'M/-', 'F/FV', 'G/G', 'FV-GV',
       'G/FV', 'AIV'], dtype=object)

In [ ]:
# Mapping of patterns for replacement (based on known statisics of how abundant each star type is in the galaxy)
pattern_map = {
    r'M/M': 'M',
    r'K/M': 'M',
    r'M-L': 'M',
    r'F-F': 'F',
    r'F/F': 'F',
    r'G/G': 'G',
    r'F/G': 'G',
    r'G/F': 'G',
    r'G-K': 'G',
    r'G/K': 'G',
    r'A/F': 'F',
    r'A-A': 'A',
    r'B-A': 'A',
    r'KV/MV': 'MV',
    r'MV-MV': 'MV',
    r'FV-GV': 'GV',
    r'Be/AO': 'AV',
    r'KeV': 'KV',
    r'mV': 'MV'
}

# Function to apply replacements
def replace_spectral(match):
    matched_text = match.group(0)
    return pattern_map[matched_text]

# Create a regex pattern that matches any key in the dictionary
combined_pattern = '|'.join(pattern_map.keys())

# Apply the replacement
experiment_5_complete_only['spectral_type'] = experiment_5_complete_only['spectral_type'].str.replace(
    combined_pattern,
    lambda m: pattern_map[m.group(0)],
    regex=True
)

In [ ]:
# checking if these changes were made to the spectral type column
experiment_5_complete_only['spectral_type'].unique()

array(['GV', 'M', 'G', 'MV', 'KV', 'FV', 'F', 'SD', 'GIV', 'K', 'AV',
       'K-V', 'A', 'FIV', 'KIII', 'M(/-)V', 'M/-V', 'M-V', 'K/-', 'M/-',
       'AIV'], dtype=object)

In [ ]:
# remove the special characters '/' and '-' and '()' from the entries
experiment_5_complete_only.loc[:, 'spectral_type'] = (experiment_5_complete_only["spectral_type"].str.replace(r'[\/\-()]', '', regex=True))

In [ ]:
# checking if these changes were made to the spectral type column
experiment_5_complete_only['spectral_type'].unique()

array(['GV', 'M', 'G', 'MV', 'KV', 'FV', 'F', 'SD', 'GIV', 'K', 'AV', 'A',
       'FIV', 'KIII', 'AIV'], dtype=object)

In [ ]:
# Identify the entrie of the dataset which do not end with sdb, WD, SD, L, T, II, III, IV, and V
no_III_IV_V_data = experiment_5_complete_only[experiment_5_complete_only['spectral_type'].notna() &
                                            ~experiment_5_complete_only["spectral_type"].str.contains(r'sdB|WD|SD|L|T', regex=True, na=False) &
                                            ~experiment_5_complete_only['spectral_type'].str.endswith(('V', 'IV', 'III', 'II'), na=False)]

no_III_IV_V_data[cols_to_show6]

,planet_name,spectral_type,star_number_per_system,stellar_effective_temp_k,stellar_mass_solar_mass,stellar_rad_solar_rad,stellar_luminosity_solar_lum
54,AU Mic b,M,1.0,3686.857143,0.501667,0.749000,0.092999
66,BD+20 594 b,G,1.0,5745.000000,1.670000,0.988041,0.954113
97,CFHTWIR-Oph 98 b,M,1.0,2320.000000,0.014700,0.245000,0.001560
120,CoRoT-25 b,F,1.0,6040.000000,1.090000,1.190000,1.690953
121,CoRoT-26 b,G,1.0,5590.000000,1.090000,1.790000,2.807005
...,...,...,...,...,...,...,...
5990,WASP-96 b,G,1.0,5556.333333,1.060000,1.050833,0.944302
5991,WASP-97 b,G,1.0,5645.000000,1.132000,1.066667,1.036581
5992,WASP-98 b,G,2.0,5519.600000,0.713800,0.708200,0.417669
5993,WASP-99 b,F,1.0,6162.000000,1.210000,1.730000,3.871407
6018,XO-6 b,F,1.0,6720.000000,1.470000,1.930000,6.815246

In [ ]:
# checking if these changes were made to the spectral type column
experiment_5_complete_only['spectral_type'].unique()

array(['GV', 'M', 'G', 'MV', 'KV', 'FV', 'F', 'SD', 'GIV', 'K', 'AV', 'A',
       'FIV', 'KIII', 'AIV'], dtype=object)

In [ ]:
# Append 'V' to the end of these entries
experiment_5_complete_only.loc[no_III_IV_V_data.index, 'spectral_type'] = no_III_IV_V_data['spectral_type'] + 'V'

In [ ]:
# checking if these changes were made to the spectral type column
experiment_5_complete_only['spectral_type'].unique()

array(['GV', 'MV', 'KV', 'FV', 'SD', 'GIV', 'AV', 'FIV', 'KIII', 'AIV'],
      dtype=object)

#### Creating habitable zone binary column

In [ ]:
# create a binary column called "habitable_zone_main_seq" for exoplanets which have a main sequence stars and a temperature range of 235K <= Teq 330K where:
# if the planet is within the habitable zone and has a main sequence luminsoty class then has value of 1
# if the planet is not within the habitable zone and has another luminosity class then has value of 0

# Precompute sqrt(Ls)
sqrt_Ls = np.sqrt(experiment_5_complete_only['stellar_luminosity_solar_lum'])

# Habitable zone boundaries with scaled inner and outer limits where a is the orbital semi major axis and Ls is the stellar luminosity class:
# For a Type MV star (0.07K sqrt(Ls) <= a <= 0.2K sqrt(Ls))
hz_inner_MV = 0.07 * sqrt_Ls
hz_outer_MV = 0.2 * sqrt_Ls
# For a Type KV star (0.1K sqrt(Ls) <= a <= 1.3K sqrt(Ls))
hz_inner_KV = 0.1 * sqrt_Ls
hz_outer_KV = 1.3 * sqrt_Ls
# For a Type GV star (0.8K sqrt(Ls) <= a <= 1.7K sqrt(Ls))
hz_inner_GV = 0.8 * sqrt_Ls
hz_outer_GV = 1.7 * sqrt_Ls
# For a Type FV star (1.5K sqrt(Ls) <= a <= 3.5K sqrt(Ls))
hz_inner_FV = 1.5 * sqrt_Ls
hz_outer_FV = 3.5 * sqrt_Ls

tolerance = 0.001

# Temperature condition
temp_condition = (
    (experiment_5_complete_only['planet_equil_temp_k'] >= 235) &
    (experiment_5_complete_only['planet_equil_temp_k'] <= 330)
)

# Individual spectral-type HZ conditions
condition_MV = (
    (experiment_5_complete_only['spectral_type'] == 'MV') &
    (experiment_5_complete_only['orbit_semi_major_axis_au'] >= hz_inner_MV - tolerance) &
    (experiment_5_complete_only['orbit_semi_major_axis_au'] <= hz_outer_MV + tolerance)
)
condition_KV = (
    (experiment_5_complete_only['spectral_type'] == 'KV') &
    (experiment_5_complete_only['orbit_semi_major_axis_au'] >= hz_inner_KV - tolerance) &
    (experiment_5_complete_only['orbit_semi_major_axis_au'] <= hz_outer_KV + tolerance)
)
condition_GV = (
    (experiment_5_complete_only['spectral_type'] == 'GV') &
    (experiment_5_complete_only['orbit_semi_major_axis_au'] >= hz_inner_GV - tolerance) &
    (experiment_5_complete_only['orbit_semi_major_axis_au'] <= hz_outer_GV + tolerance)
)
condition_FV = (
    (experiment_5_complete_only['spectral_type'] == 'FV') &
    (experiment_5_complete_only['orbit_semi_major_axis_au'] >= hz_inner_FV - tolerance) &
    (experiment_5_complete_only['orbit_semi_major_axis_au'] <= hz_outer_FV + tolerance)
)

# Combine everything
experiment_5_complete_only['habitable_zone_main_seq'] = (
    temp_condition &
    (condition_MV | condition_KV | condition_GV | condition_FV)
).astype(int)

#### Preparing dataset for modeling

In [ ]:
# Ensuring all features are normalized to be in terms of earth's and the sun's features

# Normalize the orbital period column
experiment_5_complete_only['orbital_period_day'] = experiment_5_complete_only['orbital_period_day'] / 365.26
# Normalize the planet equilibrium temperature
experiment_5_complete_only['planet_equil_temp_k'] = experiment_5_complete_only['planet_equil_temp_k'] / 255.0
# Normalize the stellar effective temperature
experiment_5_complete_only['stellar_effective_temp_k'] = experiment_5_complete_only['stellar_effective_temp_k'] / 5772.0

In [ ]:
# creating a target row called Earth which all the other rows will be compared to (similarity search)
earth_experiment_5_complete_only = pd.DataFrame({'planet_name': ['Earth'],
                                                'star_number_per_system': [1.0],
                                                'orbital_period_day': [1.0],
                                                'orbit_semi_major_axis_au':[1.0],
                                                'planet_rad_earth_rad': [1.0],
                                                'planet_mass_earth_mass': [1.0],
                                                'planet_equil_temp_k': [1.0],
                                                'spectral_type': ['GV'],
                                                'stellar_effective_temp_k': [1.0],
                                                'stellar_rad_solar_rad': [1.0],
                                                'stellar_mass_solar_mass': [1.0],
                                                'stellar_surf_grav': [1.0],
                                                'stellar_luminosity_solar_lum': [1.0],
                                                'planet_orbital_velocity': [1.0],
                                                'habitable_zone_main_seq': [1]})
earth_experiment_5_complete_only.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   planet_name                   1 non-null      object
 1   star_number_per_system        1 non-null      float64
 2   orbital_period_day            1 non-null      float64
 3   orbit_semi_major_axis_au      1 non-null      float64
 4   planet_rad_earth_rad          1 non-null      float64
 5   planet_mass_earth_mass        1 non-null      float64
 6   planet_equil_temp_k           1 non-null      float64
 7   spectral_type                 1 non-null      object
 8   stellar_effective_temp_k      1 non-null      float64
 9   stellar_rad_solar_rad         1 non-null      float64
 10  stellar_mass_solar_mass       1 non-null      float64
 11  stellar_surf_grav             1 non-null      float64
 12  stellar_luminosity_solar_lum  1 non-null      float64
 13  planet_orbital_velocity       1 non-null      float64
 14  habitable_zone_main_seq       1 non-null      int64
dtypes: float64(12), int64(1), object(2)
memory usage: 252.0+ bytes

In [ ]:
# setting the planet name as the index

# set planet name as index for earth row
earth_experiment_5_complete_only.set_index('planet_name', inplace=True)
experiment_5_complete_only.set_index('planet_name', inplace=True)

In [ ]:
# one hot encoding spectral type column

# Combine both for fitting the OneHotEncoder to prevent unseen label errors
combined_spectral_type = pd.concat([experiment_5_complete_only['spectral_type'], earth_experiment_5_complete_only['spectral_type']], ignore_index=True)

# Ensure combined_spectral_type is a DataFrame with 1 column
combined_spectral_type_df = pd.DataFrame(combined_spectral_type, columns=['spectral_type'])

# Fit the OneHotEncoder for categorical columns
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoder.fit(combined_spectral_type_df)

# Transform both the original cleaned dataset and the earth target row dataset
experiment_5_complete_only_encoded = encoder.transform(experiment_5_complete_only[['spectral_type']])
earth_experiment_5_complete_only_encoded = encoder.transform(earth_experiment_5_complete_only[['spectral_type']])

# Generate column names for the encoded columns
encoded_columns = encoder.get_feature_names_out(['spectral_type'])

# Convert to DataFrame and ensure indices match
experiment_5_complete_only_encoded = pd.DataFrame(
    experiment_5_complete_only_encoded,
    columns=encoded_columns,
    index=experiment_5_complete_only.index
)
earth_experiment_5_complete_only_encoded = pd.DataFrame(
    earth_experiment_5_complete_only_encoded,
    columns=encoded_columns,
    index=earth_experiment_5_complete_only.index
)

# Drop orignal spectral_type column since we have generated encoded columns
experiment_5_complete_only = experiment_5_complete_only.drop(columns=['spectral_type'])
earth_experiment_5_complete_only = earth_experiment_5_complete_only.drop(columns=['spectral_type'])

# Add encoded columns back into original cleaned dataset and earth
experiment_5_complete_only = pd.concat([experiment_5_complete_only, experiment_5_complete_only_encoded], axis=1)
earth_experiment_5_complete_only = pd.concat([earth_experiment_5_complete_only, earth_experiment_5_complete_only_encoded], axis=1)

In [ ]:
experiment_5_complete_only.info()

<class 'pandas.core.frame.DataFrame'>
Index: 758 entries, 55 Cnc e to pi Men c
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   star_number_per_system        758 non-null    float64
 1   orbital_period_day            758 non-null    float64
 2   orbit_semi_major_axis_au      758 non-null    float64
 3   planet_rad_earth_rad          758 non-null    float64
 4   planet_mass_earth_mass        758 non-null    float64
 5   planet_equil_temp_k           758 non-null    float64
 6   stellar_effective_temp_k      758 non-null    float64
 7   stellar_rad_solar_rad         758 non-null    float64
 8   stellar_mass_solar_mass       758 non-null    float64
 9   stellar_surf_grav             758 non-null    float64
 10  stellar_luminosity_solar_lum  758 non-null    float64
 11  planet_orbital_velocity       758 non-null    float64
 12  habitable_zone_main_seq       758 non-null    int64
 13  spectral_type_AIV             758 non-null    float64
 14  spectral_type_AV              758 non-null    float64
 15  spectral_type_FIV             758 non-null    float64
 16  spectral_type_FV              758 non-null    float64
 17  spectral_type_GIV             758 non-null    float64
 18  spectral_type_GV              758 non-null    float64
 19  spectral_type_KIII            758 non-null    float64
 20  spectral_type_KV              758 non-null    float64
 21  spectral_type_MV              758 non-null    float64
 22  spectral_type_SD              758 non-null    float64
dtypes: float64(22), int64(1)
memory usage: 158.3+ KB

In [ ]:
earth_experiment_5_complete_only.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, Earth to Earth
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   star_number_per_system        1 non-null      float64
 1   orbital_period_day            1 non-null      float64
 2   orbit_semi_major_axis_au      1 non-null      float64
 3   planet_rad_earth_rad          1 non-null      float64
 4   planet_mass_earth_mass        1 non-null      float64
 5   planet_equil_temp_k           1 non-null      float64
 6   stellar_effective_temp_k      1 non-null      float64
 7   stellar_rad_solar_rad         1 non-null      float64
 8   stellar_mass_solar_mass       1 non-null      float64
 9   stellar_surf_grav             1 non-null      float64
 10  stellar_luminosity_solar_lum  1 non-null      float64
 11  planet_orbital_velocity       1 non-null      float64
 12  habitable_zone_main_seq       1 non-null      int64
 13  spectral_type_AIV             1 non-null      float64
 14  spectral_type_AV              1 non-null      float64
 15  spectral_type_FIV             1 non-null      float64
 16  spectral_type_FV              1 non-null      float64
 17  spectral_type_GIV             1 non-null      float64
 18  spectral_type_GV              1 non-null      float64
 19  spectral_type_KIII            1 non-null      float64
 20  spectral_type_KV              1 non-null      float64
 21  spectral_type_MV              1 non-null      float64
 22  spectral_type_SD              1 non-null      float64
dtypes: float64(22), int64(1)
memory usage: 300.0+ bytes

In [ ]:
# Define weights (same order as columns)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 7.0,
    'orbit_semi_major_axis_au': 6.0,
    'planet_rad_earth_rad': 5.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 6.0,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.5,
    'stellar_mass_solar_mass': 1.5,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.0,
    'habitable_zone_main_seq': 7.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 7.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0
}

# Apply weights
for col in experiment_5_complete_only.columns:
    weight = weights.get(col, 1.0)
    experiment_5_complete_only[col] *= weight
    earth_experiment_5_complete_only[col] *= weight

model #45

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_5_complete_only)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_experiment_5_complete_only)

# Retrieve the 10 closest planet names
closest_planets_man22 = experiment_5_complete_only.index[indices[0]].tolist()
closest_distances_man22 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man22[i]} (Distance: {closest_distances_man22[i]:.4f})")

Top 10 most similar planets:
1. Kepler-22 b (Distance: 20.8885)
2. HD 224018 d (Distance: 32.3104)
3. K2-3 d (Distance: 37.4336)
4. HD 136352 d (Distance: 39.5618)
5. TRAPPIST-1 d (Distance: 39.7085)
6. Kepler-138 d (Distance: 39.9011)
7. Gliese 12 b (Distance: 40.6358)
8. LP 791-18 d (Distance: 41.1540)
9. K2-138 g (Distance: 41.5410)
10. K2-3 c (Distance: 41.5569)

model #46

In [ ]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_5_complete_only)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_experiment_5_complete_only)

# Retrieve the 10 closest planet names
closest_planets_euc22 = experiment_5_complete_only.index[indices[0]].tolist()
closest_distances_euc22 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc22[i]} (Distance: {closest_distances_euc22[i]:.4f})")

Top 10 most similar planets:
1. Kepler-22 b (Distance: 10.7934)
2. HD 224018 d (Distance: 12.6469)
3. K2-3 d (Distance: 13.5588)
4. Kepler-138 d (Distance: 14.0714)
5. K2-3 c (Distance: 14.3190)
6. K2-136 d (Distance: 14.3443)
7. TRAPPIST-1 d (Distance: 14.3985)
8. Gliese 12 b (Distance: 14.4049)
9. TOI-2095 b (Distance: 14.4645)
10. Kepler-138 c (Distance: 14.5869)